### ISSUE TITLE
finally i got running and training LoRA on M1 mac 

### ISSUE THREAD

**Issue by organicmind-pixel** [bmaltais/kohya_ss#1248]
—————

FIRST STEP

```
git clone https://github.com/bmaltais/kohya_ss.git
cd kohya_ss
```

—

```
python -m venv venv
source venv/bin/activate
```

—

```
./setup.sh
```

—

```
pip uninstall tensorboard tensorboard-data-server tensorboard-plugin-wit tensorflow tensorflow-estimator tensorflow-macos torch torchaudio torchmetrics torchvision`

```
—

```
pip install torch torchvision torchaudio torchmetrics
pip install tensorflow
```

—

```
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
pip install tensorflow torchmetrics

```
—
```
pip install -U -r requirements.txt
```

—

```
./gui.sh
```

—
```

Validating that requirements are satisfied.
All requirements satisfied.
headless: False
Load CSS...
Running on local URL:  http://127.0.0.1:7860
```

To create a public link, set `share=True` in `launch()`.

—

[ AdamW - 10files with size image 512 px - 40repeat 4epoch ] .. running well training .. but now i try study different setting to find the best result .. please share ur setting  if u running in different parameter setting..

Iv got the link tutorial in japanese website and its work fine here : https://note.com/beautiful_aigirl/n/n279e09493943

**Comment by JINHUIZHANG** [comment]
Can we only use CPU on M1 mac?

**Comment by organicmind-pixel** [comment]
> Can we only use CPU on M1 mac?

Sure i think  ,, but will slow proses on training without GPU .. i think u can change the setting [ Number of CPU threads per core ].  What spec Ur M1 Mac ? .. i use Mac studio with 32 M  
<img width="857" alt="Screenshot 2023-07-24 at 17 22 23" src="https://github.com/bmaltais/kohya_ss/assets/115919253/ea93ba08-6691-4141-affb-26f6c4878ced">

**Comment by JINHUIZHANG** [comment]
M1 pro with 32GB, any acceleration suggestion?

**Comment by organicmind-pixel** [comment]
> M1 pro with 32GB, any acceleration suggestion?

this is my detail setting training  : 

{
  "LoRA_type": "Kohya LoCon",
  "adaptive_noise_scale": 0,
  "additional_parameters": "",
  "block_alphas": "",
  "block_dims": "",
  "block_lr_zero_threshold": "",
  "bucket_no_upscale": true,
  "bucket_reso_steps": 64,
  "cache_latents": true,
  "cache_latents_to_disk": false,
  "caption_dropout_every_n_epochs": 0.0,
  "caption_dropout_rate": 0,
  "caption_extension": ".txt",
  "clip_skip": "1",
  "color_aug": false,
  "conv_alpha": 96,
  "conv_alphas": "",
  "conv_dim": 64,
  "conv_dims": "",
  "decompose_both": false,
  "dim_from_weights": false,
  "down_lr_weight": "",
  "enable_bucket": true,
  "epoch": 4,
  "factor": -1,
  "flip_aug": false,
  "full_bf16": false,
  "full_fp16": false,
  "gradient_accumulation_steps": 1.0,
  "gradient_checkpointing": false,
  "keep_tokens": 1,
  "learning_rate": 0.0001,
  "logging_dir": "./training/mqxlor/log",
  "lora_network_weights": "",
  "lr_scheduler": "cosine_with_restarts",
  "lr_scheduler_num_cycles": "",
  "lr_scheduler_power": "",
  "lr_warmup": 0,
  "max_bucket_reso": 768,
  "max_data_loader_n_workers": "0",
  "max_resolution": "768,768",
  "max_timestep": 1000,
  "max_token_length": "225",
  "max_train_epochs": "",
  "mem_eff_attn": false,
  "mid_lr_weight": "",
  "min_bucket_reso": 256,
  "min_snr_gamma": 20,
  "min_timestep": 0,
  "mixed_precision": "no",
  "model_list": "custom",
  "module_dropout": 0,
  "multires_noise_discount": 0,
  "multires_noise_iterations": 0,
  "network_alpha": 192,
  "network_dim": 128,
  "network_dropout": 0,
  "no_token_padding": false,
  "noise_offset": 0,
  "noise_offset_type": "Original",
  "num_cpu_threads_per_process": 2,
  "optimizer": "AdamW",
  "optimizer_args": "",
  "output_dir": "./training/mqxlor/output",
  "output_name": "mqxlorloconv8a",
  "persistent_data_loader_workers": false,
  "pretrained_model_name_or_path": "./training/model/aZovyaPhotoreal_v2.safetensors",
  "prior_loss_weight": 1.0,
  "random_crop": false,
  "rank_dropout": 0,
  "reg_data_dir": "",
  "resume": "",
  "sample_every_n_epochs": 1,
  "sample_every_n_steps": 0,
  "sample_prompts": "closeup Portrait of a beautiful  (((mqxlor))) woman ,  brunette, almond shaped  eyes, high cheekbones, soft  skin",
  "sample_sampler": "euler_a",
  "save_every_n_epochs": 1,
  "save_every_n_steps": 0,
  "save_last_n_steps": 0,
  "save_last_n_steps_state": 0,
  "save_model_as": "safetensors",
  "save_precision": "float",
  "save_state": false,
  "scale_v_pred_loss_like_noise_pred": false,
  "scale_weight_norms": 0,
  "sdxl": false,
  "sdxl_cache_text_encoder_outputs": false,
  "sdxl_no_half_vae": true,
  "seed": "",
  "shuffle_caption": true,
  "stop_text_encoder_training": 0,
  "text_encoder_lr": 5e-05,
  "train_batch_size": 1,
  "train_data_dir": "./training/mqxlor/img",
  "train_on_input": false,
  "training_comment": "",
  "unet_lr": 0.0001,
  "unit": 1,
  "up_lr_weight": "",
  "use_cp": false,
  "use_wandb": false,
  "v2": false,
  "v_parameterization": false,
  "vae_batch_size": 0,
  "wandb_api_key": "",
  "weighted_captions": false,
  "xformers": false
}

**Comment by JINHUIZHANG** [comment]
And have u ever met the issue with xformer, could u give me some hints on it if u can still recall it? Thanks in advance!! ![image](https://github.com/bmaltais/kohya_ss/assets/43848765/47368489-2ffb-44f5-b423-c0abd169dd79)

**Comment by JINHUIZHANG** [comment]
> 
![image](https://github.com/bmaltais/kohya_ss/assets/43848765/6c22a597-8ebe-4a78-926a-4dccb50edaae)

**Comment by organicmind-pixel** [comment]
disable Ur  : "xformers": false

**Comment by JINHUIZHANG** [comment]
![image](https://github.com/bmaltais/kohya_ss/assets/43848765/ad448a00-d451-4a42-9bdd-8b31798f5390)
i got a new issue, could u help me again, really thanks!

**Comment by organicmind-pixel** [comment]
> ![image](https://user-images.githubusercontent.com/43848765/255813845-ad448a00-d451-4a42-9bdd-8b31798f5390.png) i got a new issue, could u help me again, really thanks!

i see u not using setting that i give it to U ,,, i upload the screenshot setting parameter  ..  put the model [ v1.5 ] in ur local folder ..

<img width="1533" alt="Screenshot 2023-07-25 at 15 45 06" src="https://github.com/bmaltais/kohya_ss/assets/115919253/d8f40688-66bf-45ba-8734-a722a0c8643c">
<img width="1540" alt="Screenshot 2023-07-25 at 15 45 19" src="https://github.com/bmaltais/kohya_ss/assets/115919253/6ac2a586-4ae3-4e80-b79a-3c09fcaf4f19">
<img width="1566" alt="Screenshot 2023-07-25 at 15 45 42" src="https://github.com/bmaltais/kohya_ss/assets/115919253/13c87ae0-2164-4bbe-8ea7-d27409701042">
<img width="1568" alt="Screenshot 2023-07-25 at 15 45 56" src="https://github.com/bmaltais/kohya_ss/assets/115919253/1af3ca83-6e2f-4abe-ae61-473974f83083">

find the mistake parameter compare to the screenshot .... Ciao

**Comment by JINHUIZHANG** [comment]
![image](https://github.com/bmaltais/kohya_ss/assets/43848765/70705e45-0b0b-4b9b-b55f-ab26553e56ea)
i tried to change the parameters, which solved the last issue. But here comes a new issue as shown, any hints?

**Comment by organicmind-pixel** [comment]
hints? ... try RE install the script and start from the beginning .. thats all i can suggest U ..

**Comment by thatjimupnorth** [comment]
I got further than ever before after finding this post but it's still not working on macos. It does BLIP captioning, folder preperation, everything as normal, then after clicking Train it dumps a long list of errors in Terminal and quits.

Is there an actual macos support forum for Kohya? This is literally the only thread I can find where anyone is having the same problem as me.

**Comment by organicmind-pixel** [comment]
> I got further than ever before after finding this post but it's still not working on macos. It does BLIP captioning, folder preperation, everything as normal, then after clicking Train it dumps a long list of errors in Terminal and quits.
> 
> Is there an actual macos support forum for Kohya? This is literally the only thread I can find where anyone is having the same problem as me.

whta kind errors U have ? post it here  .. maybe we can have a look

**Comment by dmikey** [comment]
confirmed working on m1 air with 16gb unified memory. installed fresh from repo, using mac setup instructions.

make sure you have a checkpoint downloaded

just use the webui to load this config

```
{
  "LoRA_type": "Standard",
  "adaptive_noise_scale": 0,
  "additional_parameters": "",
  "block_alphas": "",
  "block_dims": "",
  "block_lr_zero_threshold": "",
  "bucket_no_upscale": true,
  "bucket_reso_steps": 64,
  "cache_latents": true,
  "cache_latents_to_disk": true,
  "caption_dropout_every_n_epochs": 0.0,
  "caption_dropout_rate": 0,
  "caption_extension": ".txt",
  "clip_skip": "1",
  "color_aug": false,
  "conv_alpha": 96,
  "conv_block_alphas": "",
  "conv_block_dims": "",
  "conv_dim": 64,
  "decompose_both": false,
  "dim_from_weights": false,
  "down_lr_weight": "",
  "enable_bucket": true,
  "epoch": 4,
  "factor": -1,
  "flip_aug": false,
  "full_bf16": false,
  "full_fp16": false,
  "gradient_accumulation_steps": 1,
  "gradient_checkpointing": false,
  "keep_tokens": 1,
  "learning_rate": 0.0001,
  "logging_dir": "/tmp/log",
  "lora_network_weights": "",
  "lr_scheduler": "cosine_with_restarts",
  "lr_scheduler_num_cycles": "",
  "lr_scheduler_power": "",
  "lr_warmup": 0,
  "max_bucket_reso": 756,
  "max_data_loader_n_workers": "0",
  "max_resolution": "512,512",
  "max_timestep": 1000,
  "max_token_length": "225",
  "max_train_epochs": "",
  "mem_eff_attn": true,
  "mid_lr_weight": "",
  "min_bucket_reso": 256,
  "min_snr_gamma": 20,
  "min_timestep": 0,
  "mixed_precision": "no",
  "model_list": "custom",
  "module_dropout": 0,
  "multires_noise_discount": 0,
  "multires_noise_iterations": 0,
  "network_alpha": 192,
  "network_dim": 128,
  "network_dropout": 0,
  "no_token_padding": false,
  "noise_offset": 0,
  "noise_offset_type": "Original",
  "num_cpu_threads_per_process": 2,
  "optimizer": "AdamW",
  "optimizer_args": "",
  "output_dir": "/tmp/out",
  "output_name": "my_model",
  "persistent_data_loader_workers": false,
  "pretrained_model_name_or_path": "/tmp/sd-v1-4.ckpt",
  "prior_loss_weight": 1.0,
  "random_crop": false,
  "rank_dropout": 0,
  "reg_data_dir": "",
  "resume": "",
  "sample_every_n_epochs": 1,
  "sample_every_n_steps": 0,
  "sample_prompts": "closeup of a person",
  "sample_sampler": "euler_a",
  "save_every_n_epochs": 1,
  "save_every_n_steps": 0,
  "save_last_n_steps": 0,
  "save_last_n_steps_state": 0,
  "save_model_as": "safetensors",
  "save_precision": "float",
  "save_state": false,
  "scale_v_pred_loss_like_noise_pred": false,
  "scale_weight_norms": 0,
  "sdxl": false,
  "sdxl_cache_text_encoder_outputs": false,
  "sdxl_no_half_vae": true,
  "seed": "",
  "shuffle_caption": true,
  "stop_text_encoder_training": 0,
  "text_encoder_lr": 5e-05,
  "train_batch_size": 1,
  "train_data_dir": "/tmp/img",
  "train_on_input": false,
  "training_comment": "",
  "unet_lr": 0.0001,
  "unit": 1,
  "up_lr_weight": "",
  "use_cp": false,
  "use_wandb": false,
  "v2": false,
  "v_parameterization": false,
  "vae_batch_size": 0,
  "wandb_api_key": "",
  "weighted_captions": false,
  "xformers": "none"
}
```

**Comment by lustfeind** [comment]
Hi friends,.. thanks for the settings, I can report that it works with my m1 pro 16GB 

Next step is training of sdxl with 1024x1024 images. I always get a MPS backend out of memory error.

Some tricks to reduce the training memory usage? 
Sad we cant use fp16.

**Comment by Jimmni** [comment]
I followed the instructions above and everything seemed to be going fine but the moment I click the Train button, python crashes. 

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'`

Any ideas?

**Comment by FullstackJack** [comment]
Have you seen this? Dude says he got training down to 1hr on Mac.
 https://github.com/bmaltais/kohya_ss/discussions/1185

**Comment by rpfile** [comment]
when i train with @dmikey 's configuration (or really any configuration) the loss goes to NaN after 200-500 steps and the training yields black images. this might be related to the LR scheduler - for some reason linear lasts a little bit longer than constant. cosine dies almost right away.

has anyone seen anything like this and is there a fix? M1 Ultra 128GB. running the latest as of 24 august with no modifications, just ./setup.sh and run.

**Comment by rpfile** [comment]
it seems this is somehow dataset dependent. raising or lowering the learning rate definitely affects whether or not this happens. lowering it to 0.00008 or 0.00005 or even 0.00001 lets things progress, but it's not clear that the increased # of steps possible before NaN is actually any different from a few hundred steps at 0.0001 (the default.)

i don't know why it is so sensitive on mps, i don't see the LR as a big issue for CUDA. despite changing the LR, eventually the loss does become NaN and i don't think i've ever finished a training run completely. i've tried rolling back 1 version of kohya_ss and this seems to have helped a little, but the problem is still there. i wonder if this is related to all the problems with the addition of SDXL support.

**Comment by dmikey** [comment]
I've tried other configs, and seem to lock up with really fine learning rates. With my configs above, I'm able to train thousands of steps with pretty decent results after. Losses of `about 0.12` getting to 1500 steps.

This is on a 16Gb M1 Mini.

**Comment by rpfile** [comment]
@dmikey by 'lock up' do you mean the loss diverges to NaN? by fine learning rates, you mean less than 0.0001 ?

i guess one possibility is that i'm still running 12.6, and apple has made changes to the MPS drivers on newer versions. at any rate i just applied the latest update for 12.6 and am re-trying with some old command lines that died almost right away. i don't think that is the issue though, because i see the same problem on my MacBook pro and it was already updated to 12.6.8. maybe i will update the MacBook to 13.5 and see if anything changes.

**Comment by rpfile** [comment]
ok, i think this is due to bugs in drivers in 12.x. upgraded to 13.5 on the MacBook and so far 1500 steps at 0.0001 without a NaN.

**Comment by dmikey** [comment]
Semaphore leak maybe? Still seem to see high loss in performance over time. Fresh boot

`4.13s/it` , after a few trains `15.25s/it`

I can train 2000 steps in under 2 hours, if attempting to train after leakage as high as 8-9 hours for the same dataset. 

If you see low performance, reboot. 

AFAIK this isn't isolated to `koyah_ss` I see the same issue with `CoreML` by apple, an leak in the model eventually doubles render times until a reboot happens.

**Comment by rpfile** [comment]
> Semaphore leak maybe? Still seem to see high loss in performance over time. Fresh boot
> 
> `4.13s/it` , after a few trains `15.25s/it`
> 
> I can train 2000 steps in under 2 hours, if attempting to train after leakage as high as 8-9 hours for the same dataset.
> 
> If you see low performance, reboot.
> 
> AFAIK this isn't isolated to `koyah_ss` I see the same issue with `CoreML` by apple, an leak in the model eventually doubles render times until a reboot happens.

this i haven't seen yet but have only put in about 12 hours worth of training so far.

**Comment by premegacool** [comment]
hello, I am a beginner, and it's my first time using Kohya on Mac M1 Max. Could you please help me with a problem I have encountered in my terminal when beginning with training? It seems there's an error related to Torch CUDA availability and former memory-efficient attention. The error message indicates that torch.cuda.is_available() is returning False, meaning that CUDA (the GPU support for PyTorch) is not available. I know that CUDA is not supported on Mac, so what should I do? 
:(
Thank You for your time.

**Comment by rpfile** [comment]
> hello, I am a beginner, and it's my first time using Kohya on Mac M1 Max. Could you please help me with a problem I have encountered in my terminal when beginning with training? It seems there's an error related to Torch CUDA availability and former memory-efficient attention. The error message indicates that torch.cuda.is_available() is returning False, meaning that CUDA (the GPU support for PyTorch) is not available. I know that CUDA is not supported on Mac, so what should I do?
> :(
> Thank You for your time.

if you use the config posted by dmikey here: https://github.com/bmaltais/kohya_ss/issues/1248#issuecomment-1670465469 you should be fine. there are a lot of code paths that were not updated for MPS and if you select some option that happens to hit that code, you'll get the CUDA error you are seeing. the options selected in dmikey's config work fine on MPS.

i think xformers does not work on MPS which might be the problem you are seeing.

**Comment by dmikey** [comment]
Here's a Command Line Version too

From `kohya_ss` root

```
$ source venv/bin/activate

$ accelerate launch --num_cpu_threads_per_process=8 "./train_network.py" --enable_bucket --min_bucket_reso=256 --max_bucket_reso=756 --pretrained_model_name_or_path="path-to-model/v1-5-pruned-emaonly.safetensors" --train_data_dir="path-to-images-root/" --resolution="512,512" --output_dir="path-to-output-model/" --logging_dir="path-to-log/log" --network_alpha="32" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=0.0001 --unet_lr=0.0005 --network_dim=64 --output_name="model_name" --lr_scheduler_num_cycles="10" --no_half_vae --learning_rate="0.0001" --lr_scheduler="cosine_with_restarts" --train_batch_size="1" --max_train_steps="1500" --save_every_n_epochs="5" --mixed_precision="no" --save_precision="float" --caption_extension=".txt" --cache_latents --optimizer_type="AdamW" --max_data_loader_n_workers="0" --max_token_length=225 --keep_tokens="1" --bucket_reso_steps=64 --min_snr_gamma=20 --mem_eff_attn --shuffle_caption --bucket_no_upscale --noise_offset=0.0
```

**Comment by remixer-dec** [comment]
For people on MacOS 12.X facing nan issues:

after `loss = loss.mean()` add
```python
if torch.isnan(loss):
    loss = torch.tensor([0.0], requires_grad=True)
````

This skips bugged loss for 1 iteration and then goes back to normal

**Comment by abesmon** [comment]
writing to inform, that I've managed to run SDXL lora training on M1 Max 16gb ram (sort of)

key points to reduce memory usage:
- use Adafactor optimizer with arguments: `scale_parameter=False relative_step=False warmup_init=False`
- very low rank (in my case I used 8 dimensions)
- Gradient accumulate steps - 1
- additional parameters: `--network_train_unet_only` (using this even on windows)
- Gradient checkpointing: true

With these changes I've got mean 93s/it and ran out of memory on 25 step. But it may be because my Mac turned sleep mode ¯\_(ツ)_/¯ 

my config file:
[config-mac_secure.json](https://github.com/bmaltais/kohya_ss/files/13301534/config-mac_secure.json)

**Comment by flov** [comment]
Thank you @abesmon I was able to start the training on my Macbook Pro M1 together with your config-mac_secure.json, however the terminal shows me to complete the training, it estimates that the training would take about 70 hours: `5/1080 [19:43<70:40:10, 236.66s/it, avr_loss=0.133]` I have 1500 regularization images, not sure if I'm doing something wrong, or if local testing on a mac just takes that long

**Comment by thatjimupnorth** [comment]
I'll be honest, I gave up trying to get any AI stuff going on my Mac at
all. There's just no getting away from the fact you need a kick ass
Graphics card for any of it to run properly. I ended up just buying an RTX
3060 and a decent power supply then repurposed an old Dell Optiplex. My Mac
is incredible for music production and video editing, but Stable Diffusion
and the family of apps that you need to run it are rooted in the PC / Linux
world at the moment.

**Comment by flov** [comment]
@thatjimupnorth I totally agree. We got the training working but it would take three days to complete it with my MacBook M1. Just yesterday though a friend pointed me to runpod.io. there you can rent a powerful gpu for a few cents an hour. In fact, the Konya repo even has a setup_runpod file which sets up the entire kohya suite on a newly setup PyTorch container and it just works flawless and fast! Amazing. I won't ever try to run these things on my mac. You can easily just rent a powerful computer for the time you need to train and then you can just shut it down again.

**Comment by thatjimupnorth** [comment]
So I'm running a kind of hybrid system. The PC which hosts the GPU is
running Stable Diffusion and that's it. Everything else is on the Mac.
Photoshop AI plugin, auto1111, even the checkpoints are on the actual Mac
SSD. I'm doing all InPainting on the Mac and upscaling in the Mac version
of Gigapixel.

**Comment by rpfile** [comment]
> @thatjimupnorth I totally agree. I managed to get the training working locally but it would take three days to complete it with my MacBook M1. Just yesterday though a friend pointed me to runpod.io. there you can rent a powerful gpu for a few cents an hour. In fact, the Konya repo even has a setup_runpod file which sets up the entire kohya suite on a newly setup PyTorch container and it just works flawless and fast! Amazing. I won't ever try to run these things on my mac. You can easily just rent a powerful computer for the time you need to train and then you can just shut it down again.

i'm confused by this, unless the GPU on the M1 MacBook you have is just really small. i have an M1 Max MacBook pro and an M1 Ultra studio and i was able to train loras in ~5h, on both machines.

**Comment by brehuang** [comment]
Hi, I'm a beginner and I just downloaded Kohya_SS today. I'm struggling a lot to figure out why my outputs are coming out as .JSON instead of .safetensors files. I've look everywhere on the internet, and haven't found a solution. I was hoping someone might be able to help me. I'm using a M1 Mac, but I'm seeing some errors when I run cd ~/kohya_ss && ./gui.sh. If someone wouldn't mind explaining as if they were talking to a 5 year old, I would deeply appreciate it.

<img width="624" alt="image" src="https://github.com/bmaltais/kohya_ss/assets/25012851/67660bf5-ed1d-4894-82ef-ceea5ef5a638">

**Comment by jeantimex** [comment]
Thank you so much @organicmind-pixel ! I have to use an older version ([v21.8.3](https://github.com/bmaltais/kohya_ss/releases/tag/v21.8.3)) of kohya_ss, otherwise, it will always throw the error with onnxruntime-gpu==1.16.0! Now I can tagging properly!

**Comment by jeantimex** [comment]
But I got the following error:

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
/Users/jeantimex/Workspace/github/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:93: UserWarning: /Users/jeantimex/miniconda3 did not contain libcudart.so as expected! Searching further paths...
  warn(
/Users/jeantimex/Workspace/github/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/Users/jeantimex/Workspace/github/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib')}
  warn(
/Users/jeantimex/Workspace/github/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:105: UserWarning: /Users/jeantimex/Workspace/github/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib: did not contain libcudart.so as expected! Searching further paths...
  warn(
/Users/jeantimex/Workspace/github/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xml/catalog'), PosixPath('/Users/jeantimex/miniconda3/etc/xml/catalog file'), PosixPath('file')}
  warn(
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
/Users/jeantimex/Workspace/github/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
  warn(
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary /Users/jeantimex/Workspace/github/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
```

**Comment by jeantimex** [comment]
After using @organicmind-pixel's config, I can successfully run the training now! Woohoo!

**Comment by jeantimex** [comment]
Just a quick update, I managed to make the latest v22.4.1 work on my Mac M1 64G.

**Step 1. Download the package and warm up python.**
```
git clone https://github.com/bmaltais/kohya_ss.git
cd kohya_ss

python -m venv venv
source venv/bin/activate
```

**Step 2. Modify requirements to avoid GPU.**

1. requirements.txt - Do not install `onnxruntime-gpu`, instead install `onnxruntime`.
```
...
# onnxruntime-gpu==1.16.0
onnxruntime==1.16.0
...
```

2. requirements_macos_arm64.txt - Delete `tensorflow-metal`.
```
torch==2.0.0 torchvision==0.15.1 -f https://download.pytorch.org/whl/cpu/torch_stable.html
xformers bitsandbytes==0.41.1
tensorflow-macos tensorboard==2.14.1
-r requirements.txt
```

**Step 3. Setup**
```
./setup.sh
```

Without GPU, I can only get 8s/it, sigh... but at least I can leave it train overnight :)

**Comment by Timbarkry** [comment]
Hello and thank you for your comment. Maybe do you know why I am getting this error? Kohya is starting in my browser and I can also do the setup of settings but if I try starting Training, I get this error:
<img width="775" alt="Bildschirm­foto 2024-01-06 um 13 00 08" src="https://github.com/bmaltais/kohya_ss/assets/41613984/bef4959c-8d8e-4af7-adf7-66a26ee76392">
<img width="496" alt="Bildschirm­foto 2024-01-06 um 13 00 33" src="https://github.com/bmaltais/kohya_ss/assets/41613984/2dbcce29-dd62-456c-b574-4d0c2ae2dc46">

I am using also Mac M1 32GB

**Comment by Daggerphobia** [comment]
@dmikey @organicmind-pixel Can you share the steps on how I can use the sample configs you shared?

**Comment by organicmind-pixel** [comment]
> @dmikey @organicmind-pixel Can you share the steps on how I can use the sample configs you shared?
> 
> I ran below command but it failed because lack of RAM issue. Any idea for this?
> 
> **My command:**
> 
> ```
> accelerate launch --num_cpu_threads_per_process=8 "./sdxl_train.py" --enable_bucket --min_bucket_reso=256 --max_bucket_reso=2048 --pretrained_model_name_or_path="<your-path>/models/Stable-diffusion/sd_xl_base_1.0.safetensors" --train_data_dir="<your-path>img" --reg_data_dir="<your-path>/reg" --resolution="512,512" --output_dir="<your-path>/model" --logging_dir="<your-path>/log" --save_model_as=safetensors --output_name="<your-name>" --lr_scheduler_num_cycles="10" --max_data_loader_n_workers="0" --learning_rate_te1="1e-05" --learning_rate_te2="1e-05" --learning_rate="1e-05" --lr_scheduler="linear" --lr_warmup_steps="769" --train_batch_size="1" --max_train_steps="1500" --save_every_n_epochs="5" --mixed_precision="no" --save_precision="float" --cache_latents --optimizer_type="AdamW" --bucket_reso_steps=64 --bucket_no_upscale --noise_offset=0.0 --no_half_vae --lowram
> ```
> 
> **Error:**
> 
> > RuntimeError: MPS backend out of memory (MPS allocated: 35.34 GB, other allocations: 938.78 MB, max allowed: 36.27 GB). Tried to allocate 25.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).

I think the script is already update  .. theres so much change on how to setup in local mac right now [ 2024 ].. what i see in ur LOG .. ur system run out of memory to running it ..

**Comment by Daggerphobia** [comment]
@organicmind-pixel I have M1max 32gb laptop. Maybe my command is totally different than yours. I tried to give lowram parameters but didn't work. Could you share your command please? I can update mine too.

**Comment by Daggerphobia** [comment]
I forgot to share in here. I fixed the problem. The below command is working successfully for my machine.

```
accelerate launch --num_cpu_threads_per_process=8 "./train_db.py" --enable_bucket --min_bucket_reso=256 --max_bucket_reso=2048 --pretrained_model_name_or_path="<your-path>/models/Stable-diffusion/realisticVisionV60B1_v60B1VAE.safetensors" --train_data_dir="<your-path>/img" --resolution="512,512" --output_dir="<your-path>/model" --logging_dir="<your-path>/log" --save_model_as=safetensors --output_name="<your-keyword>" --lr_scheduler_num_cycles="10" --max_data_loader_n_workers="0" --lr_scheduler="linear" --train_batch_size="1" --max_train_steps="600" --save_every_n_epochs="2" --mixed_precision="no" --save_precision="float" --cache_latents --optimizer_type="AdamW" --bucket_reso_steps=64 --bucket_no_upscale --noise_offset=0.0 --no_half_vae --lowram --learning_rate="1e-05"
```

**Comment by AlexBlack2202** [comment]
> LoRa training start leads to "returned non-zero exit status 1" #1946

do you have command to generate image

**Comment by lquesada** [comment]
The only thing I'd change here is:

python -m venv venv

should be:

python3.10 -m venv venv

to avoid using python3.12, which doesn't work for this.

**Comment by yuliasu** [comment]
Despite multiple attempts by a novice, the following content still appears. Can anyone help?

17:31:11-258780 INFO     Start training LoRA Standard ...                       
17:31:11-263448 INFO     Validating lr scheduler arguments...                   
17:31:11-264806 INFO     Validating optimizer arguments...                      
17:31:11-266022 ERROR    Validating /Users/suyihan/kohya_ss/config_files        
                         existence... FAILED: does not exist                    
17:31:43-543105 INFO     Start training LoRA Standard ...                       
17:31:43-545219 INFO     Validating lr scheduler arguments...                   
17:31:43-546929 INFO     Validating optimizer arguments...                      
17:31:43-548326 INFO     Validating /Users/suyihan/Desktop/AI/lora-tast/log     
                         existence and writability... SUCCESS                   
17:31:43-549687 INFO     Validating /Users/suyihan/Desktop/AI/lora-tast/model   
                         existence and writability... SUCCESS                   
17:31:43-550952 INFO     Validating runwayml/stable-diffusion-v1-5 existence... 
                         SKIPPING: huggingface.co model                         
17:31:43-552232 INFO     Validating /Users/suyihan/Desktop/AI/lora-tast/img     
                         existence... SUCCESS                                   
17:31:43-554419 INFO     Folder 30_hsu boygirl: 30 repeats found                
17:31:43-556514 INFO     Folder 30_hsu boygirl: 12 images found                 
17:31:43-557293 INFO     Folder 30_hsu boygirl: 12 * 30 = 360 steps             
17:31:43-557997 INFO     Folder 30_hsu_face boygirl: 30 repeats found           
17:31:43-559598 INFO     Folder 30_hsu_face boygirl: 12 images found            
17:31:43-560325 INFO     Folder 30_hsu_face boygirl: 12 * 30 = 360 steps        
17:31:43-561073 INFO     Regulatization factor: 1                               
17:31:43-561737 INFO     Total steps: 720                                       
17:31:43-562992 INFO     Train batch size: 1                                    
17:31:43-564587 INFO     Gradient accumulation steps: 4                         
17:31:43-565776 INFO     Epoch: 5                                               
17:31:43-567085 INFO     Max train steps: 1600                                  
17:31:43-568000 INFO     stop_text_encoder_training = 0                         
17:31:43-568489 INFO     lr_warmup_steps = 0                                    
17:31:43-569838 INFO     Saving training config to                              
                         /Users/suyihan/Desktop/AI/lora-tast/model/hsu_face_2024
                         0601-173143.json...                                    
17:31:43-571365 INFO     Executing command:                                     
                         /Users/suyihan/kohya_ss/venv/bin/accelerate launch     
                         --dynamo_backend no --dynamo_mode default --gpu_ids 0  
                         --mixed_precision no --num_processes 1 --num_machines 1
                         --num_cpu_threads_per_process 1                        
                         /Users/suyihan/kohya_ss/sd-scripts/train_network.py    
                         --config_file                                          
                         /Users/suyihan/Desktop/AI/lora-tast/model/config_lora-2
                         0240601-173143.toml                                    
Python(65566) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
17:31:43-578102 INFO     Command executed.                                      
/Users/suyihan/kohya_ss/venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'dlopen(/Users/suyihan/kohya_ss/venv/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN3c1017RegisterOperatorsD1Ev
  Referenced from: <3EF8D74C-9F11-3C9E-85DB-9E76BCCBE7A0> /Users/suyihan/kohya_ss/venv/lib/python3.10/site-packages/torchvision/image.so
  Expected in:     <03BFC270-EF54-36FC-B102-371F5164D3C9> /Users/suyihan/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    no-hostfile
But I couldn't open the help file:
    /opt/homebrew/Cellar/open-mpi/5.0.3_1/share/prte/help-hostfile.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/suyihan/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/Users/suyihan/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/Users/suyihan/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1082, in launch_command
    simple_launcher(args)
  File "/Users/suyihan/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 688, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['mpirun', '--hostfile', '/Users/suyihan/hostfile', '--npernode', '1', '-n', '1', '/Users/suyihan/kohya_ss/venv/bin/python3', '/Users/suyihan/kohya_ss/sd-scripts/train_network.py', '--config_file', '/Users/suyihan/Desktop/AI/lora-tast/model/config_lora-20240601-173143.toml']' returned non-zero exit status 250.
17:31:46-759956 INFO     Training has ended.

**Comment by yuliasu** [comment]
Despite multiple attempts by a novice, the following content still appears. Can anyone help?

/Users/suyihan/kohya_ss/venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'dlopen(/Users/suyihan/kohya_ss/venv/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN3c1017RegisterOperatorsD1Ev
  Referenced from: <3EF8D74C-9F11-3C9E-85DB-9E76BCCBE7A0> /Users/suyihan/kohya_ss/venv/lib/python3.10/site-packages/torchvision/image.so
  Expected in:     <03BFC270-EF54-36FC-B102-371F5164D3C9> /Users/suyihan/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
--------------------------------------------------------------------------
Sorry!  You were supposed to get help about:
    no-hostfile
But I couldn't open the help file:
    /opt/homebrew/Cellar/open-mpi/5.0.3_1/share/prte/help-hostfile.txt: No such file or directory.  Sorry!
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/suyihan/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/Users/suyihan/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/Users/suyihan/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1082, in launch_command
    simple_launcher(args)
  File "/Users/suyihan/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 688, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['mpirun', '--hostfile', '/Users/suyihan/hostfile', '--npernode', '1', '-n', '1', '/Users/suyihan/kohya_ss/venv/bin/python3', '/Users/suyihan/kohya_ss/sd-scripts/train_network.py', '--config_file', '/Users/suyihan/Desktop/AI/lora-tast/model/config_lora-20240601-173143.toml']' returned non-zero exit status 250.
17:31:46-759956 INFO     Training has ended.

**Comment by elistys** [comment]
Training starts, but when it finishes, there are only two files, toml and json, and no safetensors.

The settings are the same as in the screenshot.

I'm also running [python3.10 -m venv venv].

Does everyone have safetensors created after training?

**Comment by elistys** [comment]
It seems that training is possible, but has anyone actually been able to create a "LoRA that works properly on webUI"?

**Comment by mrchen1225** [comment]
I solved this problem by adding the configuration --cpu_offload_checkpointing to the additional_args option

**Comment by tuxfamily** [comment]
I just want to thanks everyone here for all these tips, I was able to build my first LoRA (for a SD1.5 model) at (a blazing fast) 1.41s/it (35 mins total!) and the result is just impressive / amazing.

My config is a studio M1 Max with 64Gb.

I use the current version of kohya_ss (v24.1.7), with python 3.10.15 and the installed libs are: 
- accelerate 0.25.0
- onnx 1.17.0
- onnxruntime 1.20.0
- tensorflow 2.16.2
- tensorflow-macos 2.16.2
- tensorflow-metal 1.1.0
- torch 2.5.1

With 16 pics and the command shared by @dmikey, like this:

```
accelerate launch --num_cpu_threads_per_process=8 "./sd-scripts/train_network.py" --enable_bucket --min_bucket_reso=256 --max_bucket_reso=756 --pretrained_model_name_or_path="models/checkpoints/fluffity-v2.5.safetensors" --train_data_dir="dataset/images/img" --resolution="512,512" --output_dir="dataset/images/model" --logging_dir="dataset/images/log" --network_alpha="32" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=0.0001 --unet_lr=0.0005 --network_dim=64 --output_name="my_lora" --lr_scheduler_num_cycles="10" --no_half_vae --learning_rate="0.0001" --lr_scheduler="cosine_with_restarts" --train_batch_size="1" --max_train_steps="1500" --save_every_n_epochs="5" --mixed_precision="no" --save_precision="float" --caption_extension=".txt" --cache_latents --optimizer_type="AdamW" --max_data_loader_n_workers="0" --max_token_length=225 --keep_tokens="1" --bucket_reso_steps=64 --min_snr_gamma=20 --mem_eff_attn --shuffle_caption --bucket_no_upscale --noise_offset=0.0
```

I got this result: 
`1500/1500 [35:10<00:00,  1.41s/it, avr_loss=0.0891]`

Then I tested my LoRA in ComfyUI and I'm very happy of the result.

Now I will try with a SDXL model 😁

**Comment by taozhiyuai** [comment]
@tuxfamily  train on gpu or cpu????

**Comment by taozhiyuai** [comment]
> confirmed working on m1 air with 16gb unified memory. installed fresh from repo, using mac setup instructions.
> 
> just use the webui to load this config
> 
> Avoid fp16 usage. and keep size down to 512x512
> 
> 1 batch, 8 cores ~ 45 seconds per step.
> 
> ```
> {
>   "LoRA_type": "Standard",
>   "adaptive_noise_scale": 0,
>   "additional_parameters": "",
>   "block_alphas": "",
>   "block_dims": "",
>   "block_lr_zero_threshold": "",
>   "bucket_no_upscale": true,
>   "bucket_reso_steps": 64,
>   "cache_latents": true,
>   "cache_latents_to_disk": true,
>   "caption_dropout_every_n_epochs": 0.0,
>   "caption_dropout_rate": 0,
>   "caption_extension": ".txt",
>   "clip_skip": "1",
>   "color_aug": false,
>   "conv_alpha": 96,
>   "conv_block_alphas": "",
>   "conv_block_dims": "",
>   "conv_dim": 64,
>   "decompose_both": false,
>   "dim_from_weights": false,
>   "down_lr_weight": "",
>   "enable_bucket": true,
>   "epoch": 4,
>   "factor": -1,
>   "flip_aug": false,
>   "full_bf16": false,
>   "full_fp16": false,
>   "gradient_accumulation_steps": 1,
>   "gradient_checkpointing": false,
>   "keep_tokens": 1,
>   "learning_rate": 0.0001,
>   "logging_dir": "/tmp/log",
>   "lora_network_weights": "",
>   "lr_scheduler": "cosine_with_restarts",
>   "lr_scheduler_num_cycles": "",
>   "lr_scheduler_power": "",
>   "lr_warmup": 0,
>   "max_bucket_reso": 756,
>   "max_data_loader_n_workers": "0",
>   "max_resolution": "512,512",
>   "max_timestep": 1000,
>   "max_token_length": "225",
>   "max_train_epochs": "",
>   "mem_eff_attn": true,
>   "mid_lr_weight": "",
>   "min_bucket_reso": 256,
>   "min_snr_gamma": 20,
>   "min_timestep": 0,
>   "mixed_precision": "no",
>   "model_list": "custom",
>   "module_dropout": 0,
>   "multires_noise_discount": 0,
>   "multires_noise_iterations": 0,
>   "network_alpha": 192,
>   "network_dim": 128,
>   "network_dropout": 0,
>   "no_token_padding": false,
>   "noise_offset": 0,
>   "noise_offset_type": "Original",
>   "num_cpu_threads_per_process": 2,
>   "optimizer": "AdamW",
>   "optimizer_args": "",
>   "output_dir": "/tmp/out",
>   "output_name": "my_model",
>   "persistent_data_loader_workers": false,
>   "pretrained_model_name_or_path": "/tmp/sd-v1-4.ckpt",
>   "prior_loss_weight": 1.0,
>   "random_crop": false,
>   "rank_dropout": 0,
>   "reg_data_dir": "",
>   "resume": "",
>   "sample_every_n_epochs": 1,
>   "sample_every_n_steps": 0,
>   "sample_prompts": "closeup of a person",
>   "sample_sampler": "euler_a",
>   "save_every_n_epochs": 1,
>   "save_every_n_steps": 0,
>   "save_last_n_steps": 0,
>   "save_last_n_steps_state": 0,
>   "save_model_as": "safetensors",
>   "save_precision": "float",
>   "save_state": false,
>   "scale_v_pred_loss_like_noise_pred": false,
>   "scale_weight_norms": 0,
>   "sdxl": false,
>   "sdxl_cache_text_encoder_outputs": false,
>   "sdxl_no_half_vae": true,
>   "seed": "",
>   "shuffle_caption": true,
>   "stop_text_encoder_training": 0,
>   "text_encoder_lr": 5e-05,
>   "train_batch_size": 1,
>   "train_data_dir": "/tmp/img",
>   "train_on_input": false,
>   "training_comment": "",
>   "unet_lr": 0.0001,
>   "unit": 1,
>   "up_lr_weight": "",
>   "use_cp": false,
>   "use_wandb": false,
>   "v2": false,
>   "v_parameterization": false,
>   "vae_batch_size": 0,
>   "wandb_api_key": "",
>   "weighted_captions": false,
>   "xformers": "none"
> }
> ```

work on CPU or GPU

**Comment by tuxfamily** [comment]
> @tuxfamily train on gpu or cpu???? 
> work on CPU or GPU

euh ... MPS? 😅 

I was monitoring the system resources during the training using iStat Menus, and I noted that the GPU was at 100% for nearly the entire duration, so I would like to say "mainly GPU".

As for the RAM usage (shared), I don't recall the exact figures, but as long as I remember, it was approximately 3 GB for SD1.5 and around 10 GB for SDXL.

Do these numbers seem incorrect to you? It's challenging to find training benchmarks, so I'm uncertain whether this performance is considered good or bad, but it seems satisfactory to me 😁 

> can you train flux?

Yes, it's on its way, but I need some time to prepare the dataset. I will keep you updated!

**Comment by taozhiyuai** [comment]
@tuxfamily thanks for help.  please help me more for the following ERR

I have followed the instructions from @organicmind-pixel 

'(kohyass) taozhiyu@Mac kohya_ss % ./setup.sh
Installing Python 3.10 if not found.
Python 3.10 found!
Installing Python-TK 3.10 if not found.
Python Tkinter 3.10 found!
Skipping git operations.
Switching to virtual Python environment.
07:30:45-458424 INFO     Python version is 3.10.15 (main, Sep  7 2024, 00:20:06) [Clang 16.0.0 (clang-1600.0.26.3)]                      
07:30:45-531832 INFO     Submodule initialized and updated.                                                                              
07:30:45-532880 INFO     Installing python dependencies. This could take a few minutes as it downloads files.                            
07:30:45-533230 INFO     If this operation ever runs too long, you can rerun this script in verbose mode to check.                       
07:30:45-533674 INFO     Kohya_ss GUI version: v24.1.7                                                                                   
07:30:45-534408 INFO     Installing modules from requirements_macos_arm64.txt...                                                         
07:30:45-534904 INFO     Installing package: torch==2.0.0 torchvision==0.15.1 -f https://download.pytorch.org/whl/cpu/torch_stable.html  
07:30:49-648779 INFO     Installing package: xformers bitsandbytes==0.41.1                                                               
07:30:58-560346 ERROR    Error running pip: install --upgrade xformers bitsandbytes==0.41.1                                              
07:30:58-561537 INFO     Installing modules from requirements.txt...                                                                     
07:30:58-563208 INFO     Installing package: -e ./sd-scripts                                                                             
07:30:59-452034 INFO     Configuring accelerate...                                                                                       
07:30:59-452907 WARNING  Could not automatically configure accelerate. Please manually configure accelerate with the option in the menu  
                         or with: accelerate config.                                                                                     
Exiting Python virtual environment.
Copying accelerate config file to: /Users/taozhiyu/.cache/huggingface/accelerate/default_config.yaml
Setup finished! Run ./gui.sh to start.'


**AND ALL THE STEPS FROM @organicmind-pixel ABOVE**


'(kohyass) taozhiyu@Mac kohya_ss % ./gui.sh
Warning: LD_LIBRARY_PATH environment variable is not set.
Certain functionalities may not work correctly.
Please ensure that the required libraries are properly configured.
 
If you use WSL2 you may want to: export LD_LIBRARY_PATH=/usr/lib/wsl/lib/
 
07:36:17-084080 INFO     Kohya_ss GUI version: v24.1.7                                                                                   
07:36:17-177607 INFO     Submodule initialized and updated.                                                                              
07:36:17-179201 INFO     Using CPU-only Torch                                                                                            
07:36:17-621625 INFO     Torch 2.0.0                                                                                                     
07:36:17-622106 WARNING  Torch reports GPU not available                                                                                 
07:36:17-622453 INFO     Python version is 3.10.15 (main, Sep  7 2024, 00:20:06) [Clang 16.0.0 (clang-1600.0.26.3)]                      
07:36:17-622910 INFO     Verifying modules installation status from /Users/taozhiyu/downloads/kohya_ss/requirements_macos_arm64.txt...   
07:36:17-623795 INFO     Installing package: torch==2.0.0 torchvision==0.15.1 -f https://download.pytorch.org/whl/cpu/torch_stable.html  
07:36:22-459021 INFO     Installing package: xformers bitsandbytes==0.41.1                                                               
07:36:31-158055 ERROR    Error running pip: install --upgrade xformers bitsandbytes==0.41.1                                              
07:36:31-159313 INFO     Verifying modules installation status from requirements.txt...                                                  
07:36:32-836206 INFO     headless: False                                                                                                 
07:36:32-857854 INFO     Loaded default GUI values from './config.toml'...                                                               
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
/Users/taozhiyu/Downloads/kohya_ss/venv/lib/python3.10/site-packages/gradio/analytics.py:106: UserWarning: IMPORTANT: You are using gradio version 4.43.0, however version 4.44.1 is available, please upgrade. 
--------
  warnings.warn('


**then start training**

'07:38:39-500011 INFO     Start training Dreambooth...                                                                                    
07:38:39-502746 INFO     Validating lr scheduler arguments...                                                                            
07:38:39-504923 INFO     Validating optimizer arguments...                                                                               
07:38:39-506851 INFO     Validating ./config.toml existence... SUCCESS                                                                   
07:38:39-508465 INFO     Validating ./logs existence and writability... SUCCESS                                                          
07:38:39-510076 INFO     Validating ./outputs existence and writability... SUCCESS                                                       
07:38:39-511906 ERROR    Validating ./models/cocktailpeanut existence... FAILED: does not exist                                          
07:38:39-513099 INFO     Validating ./models/cocktailpeanut existence... SUCCESS                                                         
07:38:39-514134 INFO     Validating ./data/reg existence... SUCCESS                                                                      
07:38:39-515143 INFO     Validating ./outputs existence... SUCCESS                                                                       
07:38:39-516170 INFO     Validating ./data/zzz existence... SUCCESS                                                                      
07:38:39-517058 ERROR    Validating ./models/vae existence... FAILED: does not exist                                                     
07:38:39-517870 INFO     Validating ./models/vae existence... SUCCESS                                                                    
07:38:39-518642 INFO     Dataset config toml file used, skipping total_steps, train_batch_size, gradient_accumulation_steps, epoch,      
                         reg_factor, max_train_steps calculations...                                                                     
07:38:39-519649 INFO     Train batch size: 1                                                                                             
07:38:39-520363 INFO     Gradient accumulation steps: 1                                                                                  
07:38:39-521073 INFO     Epoch: 1                                                                                                        
07:38:39-521728 INFO     Max train steps: 0. sd-scripts will therefore default to 1600. Please specify a different value if required.    
07:38:39-522624 INFO     lr_warmup_steps = 0                                                                                             
07:38:39-524119 INFO     Saving training config to ./outputs/new model_20241201-073839.json...                                           
07:38:39-525707 INFO     Executing command: /Users/taozhiyu/downloads/kohya_ss/venv/bin/accelerate launch --dynamo_backend no            
                         --dynamo_mode default --mixed_precision fp16 --num_processes 1 --num_machines 1 --num_cpu_threads_per_process 2 
                         /Users/taozhiyu/Downloads/kohya_ss/sd-scripts/train_db.py --config_file                                         
                         ./outputs/config_dreambooth-20241201-073839.toml                                                                
07:38:39-535636 INFO     Command executed.                                                                                               
2024-12-01 07:38:41 INFO     Loading settings from ./outputs/config_dreambooth-20241201-073839.toml...                 train_util.py:4174
                    INFO     ./outputs/config_dreambooth-20241201-073839                                               train_util.py:4193
2024-12-01 07:38:41 INFO     prepare tokenizer                                                                         train_util.py:4665
                    INFO     update token length: 150                                                                  train_util.py:4682
                    INFO     Load dataset config from ./config.toml                                                        train_db.py:67
                    WARNING  ignore following options because config file is found: train_data_dir, reg_data_dir /         train_db.py:71
                             設定ファイルが利用されるため以下のオプションは無視されます: train_data_dir, reg_data_dir                    
                    ERROR    Invalid user config / ユーザ設定の形式が正しくないようです                                config_util.py:373
Traceback (most recent call last):
  File "/Users/taozhiyu/Downloads/kohya_ss/sd-scripts/train_db.py", line 529, in <module>
    train(args)
  File "/Users/taozhiyu/Downloads/kohya_ss/sd-scripts/train_db.py", line 83, in train
    blueprint = blueprint_generator.generate(user_config, args, tokenizer=tokenizer)
  File "/Users/taozhiyu/Downloads/kohya_ss/sd-scripts/library/config_util.py", line 407, in generate
    sanitized_user_config = self.sanitizer.sanitize_user_config(user_config)
  File "/Users/taozhiyu/Downloads/kohya_ss/sd-scripts/library/config_util.py", line 370, in sanitize_user_config
    return self.user_config_validator(user_config)
  File "/Users/taozhiyu/Downloads/kohya_ss/venv/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/Users/taozhiyu/Downloads/kohya_ss/venv/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/Users/taozhiyu/Downloads/kohya_ss/venv/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['settings']
Traceback (most recent call last):
  File "/Users/taozhiyu/downloads/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/Users/taozhiyu/Downloads/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/Users/taozhiyu/Downloads/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/Users/taozhiyu/Downloads/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/Users/taozhiyu/Downloads/kohya_ss/venv/bin/python', '/Users/taozhiyu/Downloads/kohya_ss/sd-scripts/train_db.py', '--config_file', './outputs/config_dreambooth-20241201-073839.toml']' returned non-zero exit status 1.
07:38:42-662353 INFO     Training has ended.                                                                                             '

**Comment by tuxfamily** [comment]
@taozhiyuai 
> please help me more for the following ERR

Sorry, I can't help with that; it looks like a config issue that's out of my area. You might want to ask for support on Stack, Reddit, or Discord. Just remember to share your config! Good luck!

**Comment by taozhiyuai** [comment]
ok. thanks. the following  is my config. actually It is the default value.

# Copy this file and name it config.toml
# Edit the values to suit your needs

[settings]
use_shell = false # Use shell furing process run of sd-scripts oython code. Most secure is false but some systems may require it to be true to properly run sd-scripts.

# Default folders location
[model]
models_dir = "./models"                    # Pretrained model name or path
output_name = "new model"                  # Trained model output name
train_data_dir = "./data"                  # Image folder (containing training images subfolders) / Image folder (containing training images)
dataset_config = "./config.toml"             # Dataset config file (Optional. Select the toml configuration file to use for the dataset)
training_comment = "Some training comment" # Training comment
save_model_as = "safetensors"              # Save model as (ckpt, safetensors, diffusers, diffusers_safetensors)
save_precision = "bf16"                    # Save model precision (fp16, bf16, float)

[folders]
output_dir = "./outputs"    # Output directory for trained model
reg_data_dir = "./data/reg" # Regularisation directory
logging_dir = "./logs"      # Logging directory

[configuration]
config_dir = "./presets" # Load/Save Config file

[accelerate_launch]
dynamo_backend = "no"             # Dynamo backend
dynamo_mode = "default"           # Dynamo mode
dynamo_use_dynamic = false        # Dynamo use dynamic
dynamo_use_fullgraph = false      # Dynamo use fullgraph
extra_accelerate_launch_args = "" # Extra accelerate launch args
gpu_ids = ""                      # GPU IDs
main_process_port = 0             # Main process port
mixed_precision = "fp16"          # Mixed precision (fp16, bf16, fp8)
multi_gpu = false                 # Multi GPU
num_cpu_threads_per_process = 2   # Number of CPU threads per process
num_machines = 1                  # Number of machines
num_processes = 1                 # Number of processes

[basic]
cache_latents = true           # Cache latents
cache_latents_to_disk = false  # Cache latents to disk
caption_extension = ".txt"     # Caption extension
enable_bucket = true           # Enable bucket
epoch = 1                      # Epoch
learning_rate = 0.0001         # Learning rate
learning_rate_te = 0.0001      # Learning rate text encoder
learning_rate_te1 = 0.0001     # Learning rate text encoder 1
learning_rate_te2 = 0.0001     # Learning rate text encoder 2
lr_scheduler = "cosine"        # LR Scheduler
lr_scheduler_args = ""         # LR Scheduler args
lr_warmup = 0                  # LR Warmup (% of total steps)
lr_scheduler_num_cycles = 1    # LR Scheduler num cycles
lr_scheduler_power = 1.0       # LR Scheduler power
max_bucket_reso = 2048         # Max bucket resolution
max_grad_norm = 1.0            # Max grad norm
max_resolution = "512,512"     # Max resolution
max_train_steps = 0            # Max train steps
max_train_epochs = 0           # Max train epochs
min_bucket_reso = 256          # Min bucket resolution
optimizer = "AdamW8bit"        # Optimizer (AdamW, AdamW8bit, Adafactor, DAdaptation, DAdaptAdaGrad, DAdaptAdam, DAdaptAdan, DAdaptAdanIP, DAdaptAdamPreprint, DAdaptLion, DAdaptSGD, Lion, Lion8bit, PagedAdam
optimizer_args = ""            # Optimizer args
save_every_n_epochs = 1        # Save every n epochs
save_every_n_steps = 1         # Save every n steps
seed = 1234                    # Seed
stop_text_encoder_training = 0 # Stop text encoder training (% of total steps)
train_batch_size = 1           # Train batch size

[advanced]
adaptive_noise_scale = 0                  # Adaptive noise scale
additional_parameters = ""                # Additional parameters
bucket_no_upscale = true                  # Don't upscale bucket resolution
bucket_reso_steps = 64                    # Bucket resolution steps
caption_dropout_every_n_epochs = 0        # Caption dropout every n epochs
caption_dropout_rate = 0                  # Caption dropout rate
color_aug = false                         # Color augmentation
clip_skip = 1                             # Clip skip
debiased_estimation_loss = false          # Debiased estimation loss
flip_aug = false                          # Flip augmentation
fp8_base = false                          # FP8 base training (experimental)
full_bf16 = false                         # Full bf16 training (experimental)
full_fp16 = false                         # Full fp16 training (experimental)
gradient_accumulation_steps = 1           # Gradient accumulation steps
gradient_checkpointing = false            # Gradient checkpointing
huber_c = 0.1                             # The huber loss parameter. Only used if one of the huber loss modes (huber or smooth l1) is selected with loss_type
huber_schedule = "snr"                    # The type of loss to use and whether it's scheduled based on the timestep
ip_noise_gamma = 0                        # IP noise gamma
ip_noise_gamma_random_strength = false    # IP noise gamma random strength (true, false)
keep_tokens = 0                           # Keep tokens
log_tracker_config_dir = "./logs"         # Log tracker configs directory
log_tracker_name = ""                     # Log tracker name
loss_type = "l2"                          # Loss type (l2, huber, smooth_l1)
masked_loss = false                       # Masked loss
max_data_loader_n_workers = 0             # Max data loader n workers (string)
max_timestep = 1000                       # Max timestep
max_token_length = 150                    # Max token length ("75", "150", "225")
mem_eff_attn = false                      # Memory efficient attention
min_snr_gamma = 0                         # Min SNR gamma
min_timestep = 0                          # Min timestep
multires_noise_iterations = 0             # Multires noise iterations
multires_noise_discount = 0               # Multires noise discount
no_token_padding = false                  # Disable token padding
noise_offset = 0                          # Noise offset
noise_offset_random_strength = false      # Noise offset random strength (true, false)
noise_offset_type = "Original"            # Noise offset type ("Original", "Multires")
persistent_data_loader_workers = false    # Persistent data loader workers
prior_loss_weight = 1.0                   # Prior loss weight
random_crop = false                       # Random crop
save_every_n_steps = 0                    # Save every n steps
save_last_n_steps = 0                     # Save last n steps
save_last_n_steps_state = 0               # Save last n steps state
save_state = false                        # Save state
save_state_on_train_end = false           # Save state on train end
scale_v_pred_loss_like_noise_pred = false # Scale v pred loss like noise pred
shuffle_caption = false                   # Shuffle captions
state_dir = "./outputs"                   # Resume from saved training state
log_with = ""                             # Logger to use ["wandb", "tensorboard", "all", ""]
vae_batch_size = 0                        # VAE batch size
vae_dir = "./models/vae"                  # VAEs folder path
v_pred_like_loss = 0                      # V pred like loss weight
wandb_api_key = ""                        # Wandb api key
wandb_run_name = ""                       # Wandb run name
weighted_captions = false                 # Weighted captions
xformers = "none"                     # CrossAttention (none, sdp, xformers)

# This next section can be used to set default values for the Dataset Preparation section
# The "Destination training direcroty" field will be equal to "train_data_dir" as specified above
[dataset_preparation]
class_prompt = "class"                                  # Class prompt
images_folder = "/some/folder/where/images/are"         # Training images directory
instance_prompt = "instance"                            # Instance prompt
reg_images_folder = "/some/folder/where/reg/images/are" # Regularisation images directory
reg_images_repeat = 1                                   # Regularisation images repeat
util_regularization_images_repeat_input = 1             # Regularisation images repeat input
util_training_images_repeat_input = 40                  # Training images repeat input

[huggingface]
async_upload = false              # Async upload
huggingface_path_in_repo = ""     # Huggingface path in repo
huggingface_repo_id = ""          # Huggingface repo id
huggingface_repo_type = ""        # Huggingface repo type
huggingface_repo_visibility = ""  # Huggingface repo visibility
huggingface_token = ""            # Huggingface token
resume_from_huggingface = ""      # Resume from huggingface (ex: {repo_id}/{path_in_repo}:{revision}:{repo_type})
save_state_to_huggingface = false # Save state to huggingface

[samples]
sample_every_n_steps = 0   # Sample every n steps
sample_every_n_epochs = 0  # Sample every n epochs
sample_prompts = ""        # Sample prompts
sample_sampler = "euler_a" # Sampler to use for image sampling

[sdxl]
sdxl_cache_text_encoder_outputs = false # Cache text encoder outputs
sdxl_no_half_vae = true                 # No half VAE

[wd14_caption]
always_first_tags = ""                        # comma-separated list of tags to always put at the beginning, e.g. 1girl,1boy
append_tags = false                           # Append TAGs
batch_size = 8                                # Batch size
caption_extension = ".txt"                    # Extension for caption file (e.g., .caption, .txt)
caption_separator = ", "                      # Caption Separator
character_tag_expand = false                  # Expand tag tail parenthesis to another tag for character tags. `chara_name_(series)` becomes `chara_name, series`
character_threshold = 0.35                    # Character threshold
debug = false                                 # Debug mode
force_download = false                        # Force model re-download when switching to onnx
frequency_tags = false                        # Frequency tags
general_threshold = 0.35                      # General threshold
max_data_loader_n_workers = 2                 # Max dataloader workers
onnx = true                                   # ONNX
recursive = false                             # Recursive
remove_underscore = false                     # Remove underscore
repo_id = "SmilingWolf/wd-convnext-tagger-v3" # Repo id for wd14 tagger on Hugging Face
tag_replacement = ""                          # Tag replacement in the format of `source1,target1;source2,target2; ...`. Escape `,` and `;` with `\`. e.g. `tag1,tag2;tag3,tag4`
thresh = 0.36                                 # Threshold
train_data_dir = ""                           # Image folder to caption (containing the images to caption)
undesired_tags = ""                           # comma-separated list of tags to remove, e.g. 1girl,1boy
use_rating_tags = false                       # Use rating tags
use_rating_tags_as_last_tag = false           # Use rating tags as last tagging tags

[metadata]
metadata_title = ""       # Title for model metadata (default is output_name)
metadata_author = ""      # Author name for model metadata
metadata_description = "" # Description for model metadata
metadata_license = ""     # License for model metadata
metadata_tags = ""        # Tags for model metadata

**Comment by dmikey** [comment]
Sounds like Python and your installed are out of alignment. Possible if Xcode, Brew or other updated

rm -rf venv 
guy pull

And run setup again.

**Comment by jayododds** [comment]
@tuxfamily I am baffled. I have tried everything you seem to have, I have commented out versions in the requirements txt etc so that my installs of the latest of everything is there like in your list, but I still get speeds around 14.42 s/it and 20 images for SDXL is taking me any where up to 4-5 hours. I think I have everything set up properly, accelerate cnfig was set, python 3.10.x - can you walk me through your steps to achieve it all? I've tried to follow the thread but I think I am following badly :) I'm running a macbook pro m1 max with 64 GB

**Comment by RainyZombie** [comment]
@tuxfamily hei, have you or anyone actually got to train on  SDXL resolution using the MPS not cpu ( so on 1024 x 1024 equivalent)? asking  for a M3

**Comment by tuxfamily** [comment]
@RainyZombie Sorry, I can't help. I'm not a kohya_ss expert and haven't used it in months. These days, I take the easy route and use online services like Civitai. Good luck!
