### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'accelerate launch 

### ISSUE THREAD

**Issue by kalpeshranka** [bmaltais/kohya_ss#2284]
Traceback (most recent call last):
  File "/home/kalpesh/kohya_ss/venv/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/kalpesh/kohya_ss/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/kalpesh/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1627, in process_api
    result = await self.call_function(
  File "/home/kalpesh/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1173, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/kalpesh/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/kalpesh/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/home/kalpesh/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/kalpesh/kohya_ss/venv/lib/python3.10/site-packages/gradio/utils.py", line 690, in wrapper
    response = f(*args, **kwargs)
  File "/home/kalpesh/kohya_ss/kohya_gui/wd14_caption_gui.py", line 97, in caption_images
    subprocess.run(run_cmd, env=env)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'accelerate launch "/home/kalpesh/kohya_ss/sd-scripts/finetune/tag_images_by_wd14_tagger.py" --batch_size=1 --caption_extension=".txt" --caption_separator=", " --debug --frequency_tags --max_data_loader_n_workers="2" --onnx --remove_underscore --repo_id="SmilingWolf/wd-v1-4-convnextv2-tagger-v2" "/home/kalpesh/Downloads/input/images/136_Sonny/"'

**Comment by bmaltais** [comment]
Try using the code in the dev branch. Release 23.2.5 had an issue on Linux and I had to rewrite a lot of the code.

**Comment by Zhincore** [comment]
I have this issue on newest dev branch but happens in file `/home/adam/Software/kohya_ss/kohya_gui/class_command_executor.py` when training lora

**Comment by bmaltais** [comment]
What platform, Linux local, run pod, windows, etc?

**Comment by kalpeshranka** [comment]
Please find Ubuntu OS details below:
//
(base) kalpesh@kalpesh:~$ uname -r
6.5.0-27-generic
(base) kalpesh@kalpesh:~$ uname -a
Linux kalpesh 6.5.0-27-generic #28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 15 10:51:06 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
(base) kalpesh@kalpesh:~$ 
(base) kalpesh@kalpesh:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
//

Below are installation steps followed for Ubuntu OS.

git clone https://github.com/bmaltais/kohya_ss.git
cd kohya_ss
chmod +x ./setup.sh
sudo apt update -y && sudo apt install -y python3-tk
sudo apt install python3.10-venv
./setup.sh
source ./venv/bin/activate
accelerate config
=======
n which compute environment are you running?
This machine                                                                                                                                                                                                
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Which type of machine are you using?                                                                                                                                                                        
No distributed training                                                                                                                                                                                     
Do you want to run your training on CPU only (even if a GPU / Apple Silicon / Ascend NPU device is available)? [yes/NO]:no                                                                                  
Do you wish to optimize your script with torch dynamo?[yes/NO]:no                                                                                                                                           
Do you want to use DeepSpeed? [yes/NO]: no                                                                                                                                                                  
What GPU(s) (by id) should be used for training on this machine as a comma-seperated list? [all]:                                                                                                           
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Do you wish to use FP16 or BF16 (mixed precision)?                                                                                                                                                          
fp16                                                                                              =======
./gui.sh

Note:- It worked for me when I did first time installation but later I did PC OS format than later has issue , can you please help me on issue of FileNotFoundError: [Errno 2] No such file or directory: 'accelerate launch

**Comment by seadra** [comment]
Same issue on Arch Linux

```
Traceback (most recent call last):
  File "/home/user/kohya_ss/venv/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/user/kohya_ss/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/user/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1627, in process_api
    result = await self.call_function(
  File "/home/user/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1173, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/user/kohya_ss/venv/lib/python3.10/site-packages/gradio/utils.py", line 690, in wrapper
    response = f(*args, **kwargs)
  File "/home/user/kohya_ss/kohya_gui/lora_gui.py", line 1072, in train_model
    executor.execute_command(run_cmd=run_cmd, env=env)
  File "/home/user/kohya_ss/kohya_gui/class_command_executor.py", line 31, in execute_command
    self.process = subprocess.Popen(run_cmd, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'accelerate launch --mixed_precision="bf16" ...
```

Workaround is to run the `accelerate launch ...` command manually after running
```
source venv/bin/activate
```

**Comment by Zhincore** [comment]
Happened to me on Ubuntu, local venv, can't provide logs, but they are the same as above.
My workaround was to add `shell=True` to the `subprocess.Popen` call in `class_command_executor.py`

**Comment by Kadah** [comment]
Same. If I run the command manually from the venv, it works fine, only starting through the webui results in the issue. Which is the workaround I'm doing now.

( I don't use the UI anymore, switched to CLI and custom scripts after the UI update that gives me a migraine when using it for more than a few seconds. All I needed to do was load an old conifg and start a training for a quick test, which was pushing, but I planned to go to bed after this so risked it to see if the new UI was still a problem for me, and it was x_x )

Not sure if related, but TensorBoard is blank and non-functional. Has only the header across the top, rest is just white.

**Comment by bmaltais** [comment]
Let me setup a ubuntu os in WSL2 to test...

**Comment by jehe79** [comment]
Updated from 23.0.15 today - ran into the same issue as above.
Tested fetch + pull + checkout dev and fired up a config from yesterday (saved in 23.0.15).
Now in 23.1.6 my person Lora turns out as a house in the sample images when training ... 

I think it's not using the provided prompt (nor prompt.txt) since cli outputs different parameters (width, height etc) than the content of the prompt file.

Also - cli output says "num epochs: 4" even though higher value is specified in gui (which affects total training steps as well).

Lora turns out as expected i.e. not a house but the person.

**Comment by CRCODE22** [comment]
Latest update and kohya_ss does not work anymore I removed the whole venv did the setup.bat again and it did not solve the problem latest update broke lora training in kohya_ss

When I start training I get these errors:

Traceback (most recent call last):
  File "E:\anaconda3\envs\kohya_ss\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\anaconda3\envs\kohya_ss\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\kohya_ss\\venv\\Scripts\\python.exe', 'E:\\kohya_ss/sd-scripts/sdxl_train_network.py', '--bucket_no_upscale', '--bucket_reso_steps=64', '--cache_latents_to_disk', '--caption_extension=.txt', '--enable_bucket', '--


It does not give any errors when starting kohya_ss as you can see below:

21:32:18-980255 INFO     Kohya_ss GUI version: v23.1.5
21:32:19-653757 INFO     Submodule initialized and updated.
21:32:19-664755 INFO     nVidia toolkit detected
21:32:22-961518 INFO     Torch 2.1.2+cu118
21:32:22-992513 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8905
21:32:22-996521 INFO     Torch detected GPU: NVIDIA GeForce RTX 4060 Ti VRAM 16380 Arch (8, 9) Cores 34
21:32:23-004525 INFO     Python version is 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  8 2023, 10:42:25) [MSC v.1916 64 bit (AMD64)]
21:32:23-006524 INFO     Verifying modules installation status from requirements_pytorch_windows.txt...
21:32:23-010047 INFO     Verifying modules installation status from requirements_windows.txt...
21:32:23-013041 INFO     Verifying modules installation status from requirements.txt...
21:32:33-845715 INFO     headless: False
Running on local URL:  http://127.0.0.1:7862

To create a public link, set `share=True` in `launch()`.

**Comment by bmaltais** [comment]
I see you are not using the python.org version but rather anaconda… I wonder if this could be the reason. I might integrate an insecure mode to enable shell=True for exception cases… not sure why some users are not able to run it properly… my guess is Anaconda python instead of the version recommended in the Readme

**Comment by bmaltais** [comment]
> I am not using Dev branch but cloned with master branch and having issue -- of FileNotFoundError: [Errno 2] No such file or directory: 'accelerate launch " , can you please help with uninstall steps of Kohya SS , Also let me know which repository to refer for final working version.

To uninstall just delete the complete folder and git clone and install. This will give you a fresh environment.

**Comment by CRCODE22** [comment]
> I see you are not using the python.org version but rather anaconda… I wonder if this could be the reason. I might integrate an insecure mode to enable shell=True for exception cases… not sure why some users are not able to run it properly… my guess is Anaconda python instead of the version recommended in the Readme

I tried under the normal command prompt of Windows and it still does not work same errors

Do you know which older release does work? a fresh git clone and fresh environment does not work either with the dev branch.

kohya_ss was working great when I was still using an older version I forgot which exact one it was updating it and at least the 2 latest releases do not work. In the past before kohya_ss broke most versions do work.

I see stuff like the wrong accelerator version being installed and other errors.

**Comment by CRCODE22** [comment]
INFO     building U-Net                                                                                                                                                                                               sdxl_model_util.py:192
                    INFO     loading U-Net from checkpoint                                                                                                                                                                                sdxl_model_util.py:196
Traceback (most recent call last):
  File "C:\Users\CRCODE22\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\CRCODE22\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\kohya_ss\venv\Scripts\accelerate.EXE\__main__.py", line 7, in <module>
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\kohya_ss\\venv\\Scripts\\python.exe', 'E:/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', './outputs/tmpfilelora.toml', '--max_data_loader_n_workers', '0']' returned non-zero exit status 3221225477.
00:45:31-917791 INFO     Training has ended.

**Comment by bmaltais** [comment]
OK, I just pushed an update to the `dev` branch that allow you to run the gui with `--use_shell` as a parameter. This will then execute all commands using shell=True.

If this fix the issue you can then either:

    1. Start the GUI with the `--use_shell` option at all time; or
    2. Set the `use_shell` value in the config.toml file to `true`, allowing the GUI to apply user-specified settings at startup.
    - **Note:** The `--use_shell` option will take precedence over settings in the config.toml file.

**Comment by bmaltais** [comment]
OK, I think I have nailed the fix. Sort of a mix of old way of running process and auto setting shell=True for posix systems...

```
git fetch origin
git checkout dev
git pull
```

**Comment by CRCODE22** [comment]
Thank you @bmaltais you fixed it training is working again :)

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 195/195 [03:28<00:00,  1.07s/it]
2024-04-16 15:15:10 INFO     create LoRA network. base dim (rank): 64, alpha: 32                                                                                                                                                                                              lora.py:810
                    INFO     neuron dropout: p=None, rank dropout: p=None, module dropout: p=None                                                                                                                                                                             lora.py:811
                    INFO     create LoRA for Text Encoder 1:                                                                                                                                                                                                                  lora.py:902
                    INFO     create LoRA for Text Encoder 2:                                                                                                                                                                                                                  lora.py:902
2024-04-16 15:15:11 INFO     create LoRA for Text Encoder: 264 modules.                                                                                                                                                                                                       lora.py:910
2024-04-16 15:15:12 INFO     create LoRA for U-Net: 722 modules.                                                                                                                                                                                                              lora.py:918
                    INFO     enable LoRA for text encoder                                                                                                                                                                                                                     lora.py:961
                    INFO     enable LoRA for U-Net                                                                                                                                                                                                                            lora.py:966
prepare optimizer, data loader etc.
                    INFO     use Adafactor optimizer | {'scale_parameter': False, 'relative_step': False, 'warmup_init': False}                                                                                                                                        train_util.py:4047
                    WARNING  because max_grad_norm is set, clip_grad_norm is enabled. consider set to 0 / max_grad_normが設定されているためclip_grad_normが有効になります。0に設定して無効にしたほうがいいかもしれません                                               train_util.py:4075
                    WARNING  constant_with_warmup will be good / スケジューラはconstant_with_warmupが良いかもしれません                                                                                                                                                train_util.py:4079
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 195
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 82
  num epochs / epoch数: 20
  batch size per device / バッチサイズ: 4
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 1600
steps:   0%|                                                                                                                                                                                                                                                   | 0/1600 [00:00<?, ?it/s]
epoch 1/20
steps:   0%|▎                                                                                                                                                                                                                       | 2/1600 [00:34<7:35:24, 17.10s/it, avr_loss=0.0997]

**Comment by bmaltais** [comment]
Security can lead to a ton of trouble. Glad I finally could find the fix... even if it meant going back to previous less secure method... but since I now use the native sd-scripts toml tp pass the configuration instead of individual arguments it make things acceptable... so overall a win for everyone.

**Comment by CRCODE22** [comment]
@bmaltais there is another problem no matter which settings you do it will always train at 1600 not less and not more the formula to calculate based on amount of images and repeats etc does not work anymore also the sample preview generation does not work training Lora is still broken even tough it seems to be training. I would not even know where to begin in making a report for that. Any ideas what is causing this?

I am using preloaded settings that worked before until the updates and max training steps is set to 0 there is no reason in the settings it would always be exactly training at 1600 something appears to be very broken.

**Comment by CRCODE22** [comment]
There is no way that this would train at 1600 steps when max steps is set to 0.

15:58:10-967094 INFO     lora_network_weights not specified, skipping validation
15:58:10-969063 INFO     dataset_config not specified, skipping validation
15:58:10-971063 INFO     Folder 2_test woman: 195 images found
15:58:10-973060 INFO     Folder 2_test woman: 390 steps
15:58:10-974060 INFO     Total steps: 390
15:58:10-975059 INFO     Train batch size: 3
15:58:10-976063 INFO     Gradient accumulation steps: 1
15:58:10-977060 INFO     Epoch: 12

Then when it starts training it is not sticking to the above it somehow modified it to this which is very wrong:

running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 390
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 151
  num epochs / epoch数: 11
  batch size per device / バッチサイズ: 3
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 1600
steps:   0%|                                                                                                                                                                                                                                                   | 0/1600 [00:00<?, ?it/s]
epoch 1/11
steps:   0%|▍                                                                                                                                                                                                                        | 3/1600 [00:43<6:23:55, 14.42s/it, avr_loss=0.234]1

**Comment by bmaltais** [comment]
Max_steps = 0 mean it will use as-scripts internally calculated number of steps. What are you expecting to happen when you set it to 0?

**Comment by CRCODE22** [comment]
> Max_steps = 0 mean it will use as-scripts internally calculated number of steps. What are you expecting to happen when you set it to 0?

When I have set max_steps = 0 I expect that it has no limitations on the amounts of steps. Meaning that it cannot be the reason that it keeps stopping at 1600 steps like it is a max set limit. But you have already found out and fixed the error causing it by the time I wrote this comment.

**Comment by kalpeshranka** [comment]
V24.0.3 release working on my ubuntu
