### ISSUE TITLE
Training stuck at step zero

### ISSUE THREAD

**Issue by machineminded** [bmaltais/kohya_ss#2332]
@bmaltais ,

I've successfully used kohya in the past, but for some reason I'm not able to get training to start with a fresh install.

I click "Start Training" but the progress bar is stuck at 0/xxxxx steps, and no GPU resources are being used at all.

Any tips? I've tried destroying the venv and re-creating, but no dice. I am using torch  2.2.2+cu118 instead of 2.1.2+cu118 but I wouldn't think that would matter. I couldn't install 2.1.2+cu118 because it isn't found in the index.

I should note that if cache latents is enabled, it exhibits the same behavior (stuck at 0/<total images>).

**Comment by nakanakapoi** [comment]
Please help! This happens to me too, still at zero after 8 hours of Lora training. I just updated to the latest version and updated my python after not using it for a month. I just use the default options as always, the only setting I change is ticking SDXL, resolution to 1024 for SDXL and enabling no half Vae because I got NaN error. This is my output:

`23:01:47-787605 INFO     Start training LoRA Standard ...
23:01:47-788640 INFO     Validating model file or folder path
                         C:/stable-diffusion-webui/models/Stable-diffusion/sdxlUnstableDiffusers_v9DIVINITYMACHINE.safet
                         ensors existence...
23:01:47-789605 INFO     ...valid
23:01:47-790605 INFO     Validating output_dir path C:/kohya-training/yoshixldvm/model existence...
23:01:47-792086 INFO     ...valid
23:01:47-792086 INFO     Validating train_data_dir path C:/kohya-training/yoshixldvm/image existence...
23:01:47-793085 INFO     ...valid
23:01:47-794085 INFO     Validating reg_data_dir path C:/kohya-training/yoshixldvm/reg existence...
23:01:47-795084 INFO     ...valid
23:01:47-795084 INFO     Validating logging_dir path C:/kohya-training/yoshixldvm/log existence...
23:01:47-796084 INFO     ...valid
23:01:47-797087 INFO     log_tracker_config not specified, skipping validation
23:01:47-798086 INFO     resume not specified, skipping validation
23:01:47-798086 INFO     vae not specified, skipping validation
23:01:47-799084 INFO     lora_network_weights not specified, skipping validation
23:01:47-800086 INFO     dataset_config not specified, skipping validation
23:01:47-801086 INFO     Folder 100_yoshixldvm: 100 repeats found
23:01:47-802087 INFO     Folder 100_yoshixldvm: 41 images found
23:01:47-803085 INFO     Folder 100_yoshixldvm: 41 * 100 = 4100 steps
23:01:47-803085 WARNING  Regularisation images are used... Will double the number of steps required...
23:01:47-804085 INFO     Regulatization factor: 2
23:01:47-805086 INFO     Total steps: 4100
23:01:47-806085 INFO     Train batch size: 1
23:01:47-806085 INFO     Gradient accumulation steps: 1
23:01:47-807089 INFO     Epoch: 1
23:01:47-808090 INFO     max_train_steps (4100 / 1 / 1 * 1 * 2) = 8200
23:01:47-809090 INFO     stop_text_encoder_training = 0
23:01:47-809090 INFO     lr_warmup_steps = 820
23:01:47-811092 INFO     Saving training config to C:/kohya-training/yoshixldvm/model\yoshixldvm_20240418-230147.json...
23:01:47-813088 INFO     Executing command: "C:\kohya_ss\venv\Scripts\accelerate.EXE" launch --dynamo_backend no
                         --dynamo_mode default --mixed_precision fp16 --num_processes 1 --num_machines 1
                         --num_cpu_threads_per_process 2 "C:/kohya_ss/sd-scripts/sdxl_train_network.py" --config_file
                         "./outputs/tmpfilelora.toml" with shell=True
23:01:47-816091 INFO     Command executed.
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
2024-04-18 23:01:55 INFO     Loading settings from ./outputs/tmpfilelora.toml...                      train_util.py:3744
                    INFO     ./outputs/tmpfilelora                                                    train_util.py:3763
2024-04-18 23:01:55 INFO     prepare tokenizers                                                   sdxl_train_util.py:134
2024-04-18 23:01:56 INFO     update token length: 75                                              sdxl_train_util.py:159
                    INFO     Using DreamBooth method.                                               train_network.py:172
                    INFO     prepare images.                                                          train_util.py:1572
                    INFO     found directory C:\kohya-training\yoshixldvm\image\100_yoshixldvm        train_util.py:1519
                             contains 41 image files
                    INFO     found directory C:\kohya-training\yoshixldvm\reg\1_yoshixldvm contains   train_util.py:1519
                             1500 image files
                    WARNING  No caption file found for 1500 images. Training will continue without    train_util.py:1550
                             captions for these images. If class token exists, it will be used. /
                             1500枚の画像にキャプションファイルが見つかりませんでした。これらの画像に
                             ついてはキャプションなしで学習を続行します。class
                             tokenが存在する場合はそれを使います。
                    WARNING  C:\kohya-training\yoshixldvm\reg\1_yoshixldvm\person (1).png             train_util.py:1557
                    WARNING  C:\kohya-training\yoshixldvm\reg\1_yoshixldvm\person (10).png            train_util.py:1557
                    WARNING  C:\kohya-training\yoshixldvm\reg\1_yoshixldvm\person (100).png           train_util.py:1557
                    WARNING  C:\kohya-training\yoshixldvm\reg\1_yoshixldvm\person (1000).png          train_util.py:1557
                    WARNING  C:\kohya-training\yoshixldvm\reg\1_yoshixldvm\person (1001).png          train_util.py:1557
                    WARNING  C:\kohya-training\yoshixldvm\reg\1_yoshixldvm\person (1002).png... and   train_util.py:1555
                             1495 more
                    INFO     4100 train images with repeating.                                        train_util.py:1613
                    INFO     1500 reg images.                                                         train_util.py:1616
                    INFO     [Dataset 0]                                                              config_util.py:565
                               batch_size: 1
                               resolution: (1024, 1024)
                               enable_bucket: True
                               network_multiplier: 1.0
                               min_bucket_reso: 256
                               max_bucket_reso: 2048
                               bucket_reso_steps: 64
                               bucket_no_upscale: True

                               [Subset 0 of Dataset 0]
                                 image_dir: "C:\kohya-training\yoshixldvm\image\100_yoshixldvm"
                                 image_count: 41
                                 num_repeats: 100
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 keep_tokens_separator:
                                 secondary_separator: None
                                 enable_wildcard: False
                                 caption_dropout_rate: 0
                                 caption_dropout_every_n_epoches: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 is_reg: False
                                 class_tokens: yoshixldvm
                                 caption_extension: .txt

                               [Subset 1 of Dataset 0]
                                 image_dir: "C:\kohya-training\yoshixldvm\reg\1_yoshixldvm"
                                 image_count: 1500
                                 num_repeats: 1
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 keep_tokens_separator:
                                 secondary_separator: None
                                 enable_wildcard: False
                                 caption_dropout_rate: 0
                                 caption_dropout_every_n_epoches: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 is_reg: True
                                 class_tokens: yoshixldvm
                                 caption_extension: .txt


                    INFO     [Dataset 0]                                                              config_util.py:571
                    INFO     loading image sizes.                                                      train_util.py:853
100%|███████████████████████████████████████████████████████████████████████████| 1541/1541 [00:00<00:00, 32562.96it/s]
                    INFO     make buckets                                                              train_util.py:859
                    WARNING  min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is   train_util.py:876
                             set, because bucket reso is defined by image size automatically /
                             bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計
                             算されるため、min_bucket_resoとmax_bucket_resoは無視されます
                    INFO     number of images (including repeats) /                                    train_util.py:905
                             各bucketの画像枚数（繰り返し回数を含む）
                    INFO     bucket 0: resolution (320, 512), count: 100                               train_util.py:910
                    INFO     bucket 1: resolution (384, 576), count: 100                               train_util.py:910
                    INFO     bucket 2: resolution (512, 320), count: 100                               train_util.py:910
                    INFO     bucket 3: resolution (512, 384), count: 100                               train_util.py:910
                    INFO     bucket 4: resolution (512, 512), count: 4300                              train_util.py:910
                    INFO     bucket 5: resolution (512, 704), count: 300                               train_util.py:910
                    INFO     bucket 6: resolution (512, 768), count: 100                               train_util.py:910
                    INFO     bucket 7: resolution (512, 832), count: 1000                              train_util.py:910
                    INFO     bucket 8: resolution (512, 896), count: 200                               train_util.py:910
                    INFO     bucket 9: resolution (512, 960), count: 900                               train_util.py:910
                    INFO     bucket 10: resolution (512, 1088), count: 500                             train_util.py:910
                    INFO     bucket 11: resolution (704, 1088), count: 400                             train_util.py:910
                    INFO     bucket 12: resolution (704, 1152), count: 100                             train_util.py:910
                    INFO     mean ar error (without repeats): 0.0009000523534845306                    train_util.py:915
                    WARNING  clip_skip will be unexpected / SDXL学習ではclip_skipは動作しません   sdxl_train_util.py:343
                    INFO     preparing accelerator                                                  train_network.py:225
accelerator device: cuda
2024-04-18 23:01:57 INFO     loading model for process 0/1                                         sdxl_train_util.py:30
                    INFO     load StableDiffusion checkpoint:                                      sdxl_train_util.py:70
                             C:/stable-diffusion-webui/models/Stable-diffusion/sdxlUnstableDiffuse
                             rs_v9DIVINITYMACHINE.safetensors
                    INFO     building U-Net                                                       sdxl_model_util.py:192
                    INFO     loading U-Net from checkpoint                                        sdxl_model_util.py:196
2024-04-18 23:01:59 INFO     U-Net: <All keys matched successfully>                               sdxl_model_util.py:202
                    INFO     building text encoders                                               sdxl_model_util.py:205
                    INFO     loading text encoders from checkpoint                                sdxl_model_util.py:258
                    INFO     text encoder 1: <All keys matched successfully>                      sdxl_model_util.py:272
2024-04-18 23:02:00 INFO     text encoder 2: <All keys matched successfully>                      sdxl_model_util.py:276
                    INFO     building VAE                                                         sdxl_model_util.py:279
                    INFO     loading VAE from checkpoint                                          sdxl_model_util.py:284
                    INFO     VAE: <All keys matched successfully>                                 sdxl_model_util.py:287
                    INFO     Enable xformers for U-Net                                                train_util.py:2660
import network module: networks.lora
2024-04-18 23:02:01 INFO     [Dataset 0]                                                              train_util.py:2079
                    INFO     caching latents.                                                          train_util.py:974
                    INFO     checking cache validity...                                                train_util.py:984
100%|█████████████████████████████████████████████████████████████████████████| 1541/1541 [00:00<00:00, 1302846.70it/s]
                    INFO     caching latents...                                                       train_util.py:1021
100%|██████████████████████████████████████████████████████████████████████████████| 1541/1541 [07:02<00:00,  3.65it/s]
2024-04-18 23:09:04 INFO     create LoRA network. base dim (rank): 8, alpha: 1                               lora.py:810
                    INFO     neuron dropout: p=0, rank dropout: p=None, module dropout: p=None               lora.py:811
                    INFO     create LoRA for Text Encoder 1:                                                 lora.py:902
                    INFO     create LoRA for Text Encoder 2:                                                 lora.py:902
                    INFO     create LoRA for Text Encoder: 264 modules.                                      lora.py:910
                    INFO     create LoRA for U-Net: 722 modules.                                             lora.py:918
                    INFO     enable LoRA for text encoder                                                    lora.py:961
                    INFO     enable LoRA for U-Net                                                           lora.py:966
prepare optimizer, data loader etc.
2024-04-18 23:09:05 INFO     use 8-bit AdamW optimizer | {}                                           train_util.py:3889
override steps. steps for 1600 epochs is / 指定エポックまでのステップ数: 13120000
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 4100
  num reg images / 正則化画像の数: 1500
  num batches per epoch / 1epochのバッチ数: 8200
  num epochs / epoch数: 1600
  batch size per device / バッチサイズ: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 13120000
steps:   0%|                                                                              | 0/13120000 [00:00<?, ?it/s]
epoch 1/1600
steps:   0%|                                              | 229/13120000 [11:3steps:   0%|                                              | 230/13120000 [11:4steps:   0%|                                              | 230/13120000 [11:4steps:   0%|                                              | 231/13120000 [11:4steps:   0%|                                    steps:   0%|                                           | 8200/13120000 [7:09:28<11445:28:32,  3.14s/it, avr_loss=0.124]
saving checkpoint: C:/kohya-training/yoshixldvm/model\yoshixldvm-000001.safetensors

epoch 2/1600
steps:   0%|                                           | 8346/13120000 [7:17:02<11443:20:05,  3.14s/it, avr_loss=0.124]`

**Comment by nakanakapoi** [comment]
In my case, the training did start and went beyond zero, but still at zero percent after 8 hours. Is my step too much? Did my 1500 regularisation images affect this? But in my old training it should almost be done by now.

**Comment by bmaltais** [comment]
Might be one of the bug I just fixed in the dev branch. Please try the dev brnch code to see if it help...

**Comment by machineminded** [comment]
> Might be one of the bug I just fixed in the dev branch. Please try the dev brnch code to see if it help...
> 
> ```
> fir fetch origin,
> git checkout dev
> git pull
> ```

This yields a new error:

``` 
ValueError: Could not find the operator torchvision::nms. Please make sure you have already registered the operator and (if registered from C++) loaded it via torch.ops.load_library.
```

**Comment by bmaltais** [comment]
Not sure it will make a difference but try deleting the vent folder and rerun setup… there is something I can’t explain causing this.

**Comment by machineminded** [comment]
I reset to master as of today (v24.0.6), re-created the venv, but the "stuck at step zero" issue remains.   I checked "Cache latents" and it's stuck, if I disable that, training remains stuck at step zero as well.

**Comment by machineminded** [comment]
I'm using latest pytorch (2.2.2+cu121) with the matching xformers, if that makes any difference.

**Comment by bmaltais** [comment]
Possibly… the gui requirements are for torch 2.1… I don’t know if kohya actually support torch 2.2

**Comment by machineminded** [comment]
For some reason trying to install pytorch for Windows with either CUDA 11.8 or 12.x results in this error

```
ERROR: Could not find a version that satisfies the requirement torch==2.1.2+cu118 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch==2.1.2+cu118
```
Though I'm pretty sure it is in the index...

**Comment by bmaltais** [comment]
Simply delete the venv folder and run setup.bat to re-install everything.

**Comment by Nova-lotus** [comment]
Getting this too, re-installed like 5 times already, it's just stuck at step 0

**Comment by bmaltais** [comment]
Perhaps there was a PyTorch module update that is now causing this error? I will try deleting my vent and run setup again. Have you tried doing this?

**Comment by Nova-lotus** [comment]
I have tried yes, been trying since yesterday

**Comment by machineminded** [comment]
@bmaltais I destroyed `venv` and ran `setup.bat`.  After the installation was complete, I launched the GUI and received this error now when starting the training:

```
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
```

Is this due to my training configuration or somethin else?

**Comment by bmaltais** [comment]
@Nova-lotus have you tried doing a `pip cache purge` and then try to run setup.bat? I just did and everything install fine for me.

**Comment by machineminded** [comment]
> @machineminded This is something kohya can answer probable... I have no idea why his sd-scripts programs are putting this out... nut are you training with fp16 or bf16? Make sure to set the right value in the Accelerate accordion.

I've tried both fp16 and bf16  - same error.

**Comment by Nova-lotus** [comment]
> @Nova-lotus have you tried doing a `pip cache purge` and then try to run setup.bat? I just did and everything install fine for me.

Nope, just tried that, didn't work, still stuck at step 0, tried all different parameters and still nothing

**Comment by bmaltais** [comment]
Try one of my test config in the `./test/config` folder. They are test I use to validate that things still work. Try one that would be for what you are trying to do and see if it will start training... might give you a hint as to what you might be doing wrong...

Just load and run the config. Should work out of the box... mostly unless I left something specific to my computer... but should not in most cases.

**Comment by Nova-lotus** [comment]
Yeah those are what I was trying, tried like 3 of them, but I'll check more later and see if that'd do anything

**Comment by bmaltais** [comment]
OK... what I you trying to train? Which test file did not work. I will test it on my windows and linux system. Do you train on linux or windows?

**Comment by Nova-lotus** [comment]
I'm on windows, just a normal 1024x1024 SDXL Lora using 20 images, I used

- SDXL - LoRA AI_Now prodigy v1.0
- SDXL - LoRA AI_Now ADamW v1.0
- SDXL - LoRA adafactor v1.0

But neither 3 worked, this is my first time using Kohya_ss but I used Onetrainer and it didn't really suit my taste so I was considering trying this.

**Comment by bmaltais** [comment]
OK... So it appear to train fine after adjusting the Bucket resolution steps to 32...

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/cfedf198-9b0e-40ab-8c13-fca65366f162)

Here is the updated json.

[SDXL-Standard-Adafactor.json](https://github.com/bmaltais/kohya_ss/files/15068432/SDXL-Standard-Adafactor.json)

Training at 1.26s/it:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/8dfc7eb8-e72b-4740-bdb7-49aa3c3da9e7)

**Comment by nakanakapoi** [comment]
The update fixed it for me. I restored my working backup, then updated from there. Curiously now my training only takes 1 hours instead of the usual 8 hours. The downside is the lora effect is much weaker. I did not change the default parameter except the resolution and SDXL. so maybe I can tweak some setting to fix this.

**Comment by nakanakapoi** [comment]
> The update fixed it for me. I restored my working backup, then updated from there. Curiously now my training only takes 1 hours instead of the usual 8 hours. The downside is the lora effect is much weaker. I did not change the default parameter except the resolution and SDXL. so maybe I can tweak some setting to fix this.

I found the probable culprit. In the latest update the "max trains steps" is defaulted to 1600 whereby in my old training the step is usually about 8000+

**Comment by Nova-lotus** [comment]
> OK... So it appear to train fine after adjusting the Bucket resolution steps to 32...


Nope, and I tried all the other, though I tried SD1.5 and it worked, I still have no Idea what's wrong but I'll keep trying different parameters

**Comment by Nova-lotus** [comment]
So somehow I got it to work? I have no idea what I did but I just kept trying everything (Even installing Triton which broke everything, but hail the backups) and now even though it's somewhat slow it still works which I'm happy for

**Comment by machineminded** [comment]
I haven't been able to get this to work yet.  Which is so weird, because I've trained a lot of LoRAs using this GUI + kohya combo.  I've tried resetting to main, blowing away the venv, and running setup.bat.  No dice.  Tried the sample trainings per @bmaltais , but it is still stuck at zero.  Do I have to use CUDA 11.8?

**Comment by machineminded** [comment]
After running setup.bat, I run option 1 (install kohya_ss), then when I run it, I get xformers is missing.  So I try to manually install that and then it wants to install the non-cuda version of pytorch... 😕  Can you help?  Shouldn't the setup.bat handle everything for me?  

@bmaltais

**Comment by bmaltais** [comment]
You 100% need cuda 11.8. 12 will NOT work.

**Comment by machineminded** [comment]
Alright - I've got 11.8 installed and now I'm back to the 

```
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
```
error.  Should I open a ticket on kohya's repo?

**Comment by bmaltais** [comment]
I really wish I could help. There is obviously something causing this on your system… but what? I don’t think it is related so the scripts themselves of a bunch of other users would echo the same error you are getting… but beside yourself I have not seen many.

Hope you can find what software or config is causing this.

**Comment by machineminded** [comment]
No worried @bmaltais , I'll keep plugging away at it.  I opened an issue on kohya's repo.  It has worked in the past, so I'm sure I can get it working somehow!

**Comment by machineminded** [comment]
Hey @bmaltais , I finally have some resolution on this.  I uninstalled _**everything**_: python, nvidia drivers, cuda, anything nvidia related, Microsoft VS redistributables.  And started from scratch, and now it works.  Thanks!

**Comment by bmaltais** [comment]
Fantastic. I am glad you could fix it.

**Comment by pbberlin** [comment]
also make sure, that in your configuration JSON file,
both *_precision settings are set to 'bf16'
