### ISSUE TITLE
Unified Installer discussion

### ISSUE THREAD

**Issue by bmaltais** [bmaltais/kohya_ss#756]
This issue is to work out bugs/enhancements related to the newly introduced Universal Installer. This installer will support installation ob Linux, MacOS and Windows.

Please give it a try as we need multiple testers to validate that the script perform as well or better than the previous solutions on all platforms. THe user experience is also significantly changed.

Give us feedback on what you think, what worke well and what could be improved.

Huge thanks to @jstayco for his hard work on this. He is a great example of how community comes together to improve projects and move them forward for the benefits of others!

You can join the discussion about how to test and report results here also: https://github.com/bmaltais/kohya_ss/discussions/715

**Comment by bmaltais** [comment]
@jstayco I tried training with AdamW8bit on windows and got a bitsandbytes error. Is it possible the bitsandbytes files are not getting copied by the launcher?

**Comment by bmaltais** [comment]
I think I found the issue... the wrong version of bitsandbytes is installes... will push an update for that,,,

**Comment by jstayco** [comment]
For your reference, if you need to change file paths for that it's controlled right here: https://github.com/bmaltais/kohya_ss/blob/dev/launcher.py#L1257

**Comment by bmaltais** [comment]
OK... I think launcher.py is not copying the bitsandbytes files as it should. I "properly" manually copied the files this time and now the error is different...

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary D:\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
Traceback (most recent call last):
  File "D:\kohya_ss\train_network.py", line 773, in <module>
    train(args)
  File "D:\kohya_ss\train_network.py", line 211, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "D:\kohya_ss\library\train_util.py", line 2528, in get_optimizer
    import bitsandbytes as bnb
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\autograd\_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 43, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 39, in get_instance
    cls._instance.initialize()
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 33, in initialize
    self.lib = ct.cdll.LoadLibrary(str(binary_path))            # $$$
  File "C:\Users\berna\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\berna\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```

No idea why it is failing now ;-(

**Comment by jstayco** [comment]
Could you get me a list of files that are supposed to be installed if its bitsandbytes stuff missing? I'm looking at the source and destination in the linked file above and it passes the common sense test.

**Comment by bmaltais** [comment]
Are the bitsandbytes files copied before the requirements files are installed or after? THe function name lead me to beleive they are installed before... when they need to be installed after?

**Comment by jstayco** [comment]
To be honest I was just as confused, but that order of operations came from one of the early docker implementations that was presented to us. It should definitely be after, right? If you want an easy quick  test just switch the function order in main().

**Comment by bmaltais** [comment]
I tested moving it after and it fixed that issue... but now there is a new one:

```
use 8-bit AdamW optimizer | {}
Traceback (most recent call last):
  File "D:\kohya_ss\train_network.py", line 773, in <module>
    train(args)
  File "D:\kohya_ss\train_network.py", line 211, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "D:\kohya_ss\library\train_util.py", line 2532, in get_optimizer
    optimizer_class = bnb.optim.AdamW8bit
AttributeError: module 'bitsandbytes' has no attribute 'optim'
Traceback (most recent call last):
  File "C:\Users\berna\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\berna\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 923, in launch_command
    simple_launcher(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```

**Comment by jstayco** [comment]
I'll patch the order of ops on that one. My best guess there is that if an attr wasn't found, maybe a .dll is missing outside of the ones we copy?

**Comment by bmaltais** [comment]
No, all the 4 files are there... the files were copied before bitsandbytes was installed and were overwritten when pip installed the module...

**Comment by bmaltais** [comment]
I really don't understand why things work fine then I go back to the pre- branch but fail... I did a diff between the pip freeze output and there is hardly any differences.

**Comment by bmaltais** [comment]
I don't know. THe branch with the unified installer just won't train in 8bit mode. No idea why that is...

**Comment by jstayco** [comment]
Do you think you could get me a pip list + file tree of the venv folder? I'll try to run the install on the Windows machine I have and see if I can spot the difference. 
The command to run in cmd for this is `tree /a /f > file_tree.doc`. You run that command from the venv's site-packages folder to get the relevant files.

**Comment by jstayco** [comment]
Another question is do you see the same behavior on Torch 1 and Torch 2? Or just one in particular?

**Comment by bmaltais** [comment]
OK, I ran an experiment. I applied only a few files from the unified installer on top of the working pre-Unified_installer branch to see if things would work again and they did. Here are the files I copied:

- kohya_gui.py
- launcher.py
- setup.bat
- setup.ps1
- setup.sh
- install_config.yml

The installer did not properly copy the 4 bitsandbytes files so I had to re-copy them.

Then running the GUI I was able to train with no issue... So the problem must be related to other files that were not supposed to be updated... I feel like replacing all the files in the current pre-unified_installer branch with this minimalist working set of files so we get back to a working state?

**Comment by bmaltais** [comment]
If you want to test the minimal set of files to compare you can checkout branch `test_unified_installer`

**Comment by wzgrx** [comment]
> If you want to test the minimal set of files to compare you can checkout branch `test_unified_installer`
I tried, there were many errors reported

Beginning main function.
Installing Python 3.10. This could take a few minutes.
Chocolatey v1.3.0
Chocolatey detected you are not running from an elevated command shell
 (cmd/powershell).

 You may experience errors - many functions/packages
 require admin rights. Only advanced users should run choco w/out an
 elevated shell. When you open the command shell, you should ensure
 that you do so with "Run as Administrator" selected. If you are
 attempting to use Chocolatey in a non-administrator setting, you
 must select a different location other than the default install
 location. See
 https://docs.chocolatey.org/en-us/choco/setup#non-administrative-install
 for details.


 Do you want to continue?([Y]es/[N]o): y

Installing the following packages:
python
By installing, you accept licenses for the packages.
Progress: Downloading python3 3.10.0... 100%
Progress: Downloading vcredist2015 14.0.24215.20170201... 100%
Progress: Downloading vcredist140 14.34.31938... 100%
Progress: Downloading chocolatey-core.extension 1.4.0... 100%
Progress: Downloading chocolatey-compatibility.extension 1.0.0... 100%
Progress: Downloading KB3033929 1.0.5... 100%
Progress: Downloading chocolatey-windowsupdate.extension 1.0.5... 100%
Progress: Downloading KB3035131 1.0.3... 100%
Progress: Downloading KB2999226 1.0.20181019... 100%
Progress: Downloading python 3.10.0... 100%
python not installed. An error occurred during installation:
 对路径“C:\ProgramData\chocolatey\lib\chocolatey-compatibility.extension\extensions”的访问被拒绝。
python package files install failed with exit code 1. Performing other installation steps.
The install of python was NOT successful.
python not installed. An error occurred during installation:
 对路径“C:\ProgramData\chocolatey\lib\chocolatey-compatibility.extension\extensions”的访问被拒绝。
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 对路径“C:\ProgramData\chocolatey\lib-bad”的访问被拒绝。
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 对路径“C:\ProgramData\chocolatey\lib-bad”的访问被拒绝。
Maximum tries of 3 reached. Throwing error.
Cannot create directory "C:\ProgramData\chocolatey\lib-bad". Error was:
System.UnauthorizedAccessException: 对路径“C:\ProgramData\chocolatey\lib-bad”的访问被拒绝。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   在 System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   在 chocolatey.infrastructure.filesystem.DotNetFileSystem.<>c__DisplayClass64.<create_directory>b__63()
   在 chocolatey.infrastructure.tolerance.FaultTolerance.<>c__DisplayClass1.<retry>b__0()
   在 chocolatey.infrastructure.tolerance.FaultTolerance.retry[T](Int32 numberOfTries, Func`1 function, Int32 waitDurationMilliseconds, Int32 increaseRetryByMilliseconds, Boolean isSilent)
   在 chocolatey.infrastructure.filesystem.DotNetFileSystem.create_directory(String directoryPath)
   在 chocolatey.infrastructure.filesystem.DotNetFileSystem.create_directory_if_not_exists(String directoryPath, Boolean ignoreError)

Chocolatey installed 0/0 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at
 https://chocolatey.org/compare
对路径“C:\ProgramData\chocolatey\lib-bad”的访问被拒绝。

**Comment by wzgrx** [comment]
> If you want to test the minimal set of files to compare you can checkout branch `test_unified_installer`

I tried, there were many errors reported

y installing, you accept licenses for the packages.
python v3.10.0 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

Chocolatey installed 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Warnings:
 - python - python v3.10.0 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
Install-Python310 : Failed to install. Please ensure Python 3.10 is installed and available in $PATH.
所在位置 G:\Soft\test\kohya_ss\setup.ps1:2181 字符: 17
+                 Install-Python310 -Interactive:$Params.interactive
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Install-Python310

PowerShell script failed or was blocked. Falling back to Python script.


WARNING: This MSI requires uninstall prior to installing a different version. Please ask the package maintainer(s) to add a check in the chocolateyInstall.ps1 script and uninstall if the software is installed. This is most likely an issue with the 'python3' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly.
ERROR: Running ["C:\ProgramData\chocolatey\lib\python3\tools\python-3.10.0-amd64.exe" /quiet InstallAllUsers=1 PrependPath=1 TargetDir="C:\Python310" ] was not successful. Exit code was '1638'. Exit code indicates the following: This MSI requires uninstall prior to installing a different version. Please ask the package maintainer(s) to add a check in the chocolateyInstall.ps1 script and uninstall if the software is installed. This is most likely an issue with the 'python3' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly..
The install of python3 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\python3\tools\chocolateyInstall.ps1'.
 See log for details.

I had to stop testing after installing a lot of things on the C drive

**Comment by wzgrx** [comment]
> If you want to test the minimal set of files to compare you can checkout branch `test_unified_installer`

Each reinstallation will result in different errors

**Comment by bmaltais** [comment]
I never tested the installer on a fresh windows machine... mine had all those pre-req already installed manually... thanks for testing this out.

**Comment by wzgrx** [comment]
> 我从未在新的Windows机器上测试过安装程序...我的已经手动安装了所有这些预要求......感谢您对此进行测试。

It's okay, I'm just testing

**Comment by alicx1** [comment]
I just tried the installer on win11 (python 3.11.3) and it dosent work for me. first time installing it btw.
this is the error i have:
```
PS C:\Khoya> git clone https://github.com/bmaltais/kohya_ss.git
Cloning into 'kohya_ss'...
remote: Enumerating objects: 6541, done.
remote: Counting objects: 100% (6541/6541), done.
remote: Compressing objects: 100% (2012/2012), done.
remote: Total 6541 (delta 4547), reused 6407 (delta 4457), pack-reused 0
Receiving objects: 100% (6541/6541), 4.86 MiB | 28.42 MiB/s, done.
Resolving deltas: 100% (4547/4547), done.
PS C:\Khoya> cd kohya_ss
PS C:\Khoya\kohya_ss> .\setup.bat
Warning: Python version 3.10.9 is recommended.
Do you want to uninstall previous versions of torch and associated files before installing? Usefull if you are upgrading from torch 1.12.1 to torch 2.0.0 or if you are downgrading from torch 2.0.0 to torch 1.12.1.
[1] - Yes
[2] - No (recommanded for most)
Enter your choice (1 or 2): 1
WARNING: Skipping xformers as it is not installed.
WARNING: Skipping torch as it is not installed.
WARNING: Skipping torchvision as it is not installed.
WARNING: Skipping triton as it is not installed.
Please choose the version of torch you want to install:
[1] - v1 (torch 1.12.1) (Recommended)
[2] - v2 (torch 2.0.0) (Experimental)
Enter your choice (1 or 2): 1
WARNING: Skipping bitsandbytes as it is not installed.
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu116 (from versions: 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==1.12.1+cu116

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Ignoring bitsandbytes: markers 'sys_platform == "darwin" or sys_platform == "linux"' don't match your environment
Ignoring gradio: markers 'sys_platform == "darwin"' don't match your environment
Ignoring tensorboard: markers 'sys_platform == "darwin"' don't match your environment
Ignoring huggingface-hub: markers 'sys_platform == "darwin"' don't match your environment
Processing c:\khoya\kohya_ss
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting accelerate==0.18.0
  Using cached accelerate-0.18.0-py3-none-any.whl (215 kB)
Collecting albumentations==1.3.0
  Using cached albumentations-1.3.0-py3-none-any.whl (123 kB)
Collecting altair==4.2.2
  Using cached altair-4.2.2-py3-none-any.whl (813 kB)
Collecting bitsandbytes==0.35.0
  Using cached bitsandbytes-0.35.0-py3-none-any.whl (62.5 MB)
Collecting dadaptation==1.5
  Using cached dadaptation-1.5.tar.gz (8.3 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting diffusers[torch]==0.10.2
  Using cached diffusers-0.10.2-py3-none-any.whl (503 kB)
Collecting easygui==0.98.3
  Using cached easygui-0.98.3-py2.py3-none-any.whl (92 kB)
Collecting einops==0.6.0
  Using cached einops-0.6.0-py3-none-any.whl (41 kB)
Collecting ftfy==6.1.1
  Using cached ftfy-6.1.1-py3-none-any.whl (53 kB)
Collecting gradio==3.28.1
  Using cached gradio-3.28.1-py3-none-any.whl (17.3 MB)
Collecting lion-pytorch==0.0.6
  Using cached lion_pytorch-0.0.6-py3-none-any.whl (4.2 kB)
Collecting opencv-python==4.7.0.68
  Using cached opencv_python-4.7.0.68-cp37-abi3-win_amd64.whl (38.2 MB)
Collecting pytorch-lightning==1.9.0
  Using cached pytorch_lightning-1.9.0-py3-none-any.whl (825 kB)
Collecting safetensors==0.2.6
  Using cached safetensors-0.2.6-cp311-cp311-win_amd64.whl (268 kB)
Collecting tensorboard==2.10.1
  Using cached tensorboard-2.10.1-py3-none-any.whl (5.9 MB)
Collecting tk==0.1.0
  Using cached tk-0.1.0-py3-none-any.whl (3.9 kB)
Collecting toml==0.10.2
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting transformers==4.26.0
  Using cached transformers-4.26.0-py3-none-any.whl (6.3 MB)
Collecting voluptuous==0.13.1
  Using cached voluptuous-0.13.1-py3-none-any.whl (29 kB)
Collecting wandb==0.15.0
  Using cached wandb-0.15.0-py3-none-any.whl (2.0 MB)
Collecting fairscale==0.4.13
  Using cached fairscale-0.4.13.tar.gz (266 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting requests==2.28.2
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting timm==0.6.12
  Using cached timm-0.6.12-py3-none-any.whl (549 kB)
Collecting huggingface-hub==0.13.3
  Using cached huggingface_hub-0.13.3-py3-none-any.whl (199 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.10.1 (from versions: 2.12.0rc0, 2.12.0rc1, 2.12.0)
ERROR: No matching distribution found for tensorflow==2.10.1

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Copy C:\Khoya\kohya_ss\bitsandbytes_windows\cextension.py to C:\Khoya\kohya_ss\venv\Lib\site-packages\bitsandbytes
Copy C:\Khoya\kohya_ss\bitsandbytes_windows\libbitsandbytes_cpu.dll to C:\Khoya\kohya_ss\venv\Lib\site-packages\bitsandbytes
Copy C:\Khoya\kohya_ss\bitsandbytes_windows\libbitsandbytes_cuda116.dll to C:\Khoya\kohya_ss\venv\Lib\site-packages\bitsandbytes
Copy C:\Khoya\kohya_ss\bitsandbytes_windows\main.py to C:\Khoya\kohya_ss\venv\Lib\site-packages\bitsandbytes\cuda_setup
File not found error: [Errno 2] No such file or directory: 'C:\\Khoya\\kohya_ss\\venv\\Lib\\site-packages\\bitsandbytes\\cuda_setup'
'accelerate' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
```

**Comment by bmaltais** [comment]
Hello @alicx1 you appear to be using the pre-unified_installer version. Still interesting to know why it is failing.

1st question, did you install the pre-requirements for python 3.10.9 on your computer? I see a Warning: Python version 3.10.9 is recommended.

This might be why things are failing to install...

**Comment by alicx1** [comment]
> 

@bmaltais  sorry wrong info. i just used the wrong python version. i have many installed and it's easy to confuse

**Comment by jstayco** [comment]
> OK, I ran an experiment. I applied only a few files from the unified installer on top of the working pre-Unified_installer branch to see if things would work again and they did. Here are the files I copied:

    kohya_gui.py
    launcher.py
    setup.bat
    setup.ps1
    setup.sh
    install_config.yml
    requirements_macos.txt

The installer did not properly copy the 4 bitsandbytes files so I had to re-copy them.

Then running the GUI I was able to train with no issue... So the problem must be related to other files that were not supposed to be updated... I feel like replacing all the files in the current pre-unified_installer branch with this minimalist working set of files so we get back to a working state?

The only ones I can think of that would introduce an issue are the .dll files. Just roll those back and see if that issue disappears. All other files are fine.

**Comment by bmaltais** [comment]
I will revert the dev branch to what it was before and copy the files above in there since this appear to be all that is really needed to bring the new unified launcher. THe we can remove unnecessary files from dev as required... but at least the base will be solid

**Comment by jstayco** [comment]
Rope in my new fixes into the setup.ps1 before you do that, so the enhancements aren't lost.

**Comment by jstayco** [comment]
> I will revert the dev branch to what it was before and copy the files above in there since this appear to be all that is really needed to bring the new unified launcher. THe we can remove unnecessary files from dev as required... but at least the base will be solid

Make sure the files you include to bring in are:
kohya_gui.py
launcher.py
setup.bat
setup.ps1
setup.sh
install_config.yml
requirements.txt
requirements_macos.txt
README.md
CONTRIBUTING.md

After you do that and let me know, I'll go back in and remove the extras that can get deleted and change the scripts that you wanted to keep to point at the new stuff.

**Comment by bmaltais** [comment]
Some of the files that were removed should be kept for windows user legacy gui.bat/ps1.

**Comment by jstayco** [comment]
Don't worry, just cleaning up things that are now handled in launcher.py and re-aiming gui stuff to go through launcher.py so they get the features too. I think I understand your requirements and it'll be a PR for review of course.

**Comment by bmaltais** [comment]
OK, while trying to revert all the changes to dev I think I found out the source of the iossue with training... and I apparently did not. Man, I really don't know what is causing all this trouble with training. Something is messing things up but I can't figure out why. Maybe I will just commit the broken solution that sort of work and we fix it without braking training... without functional training there is no point to have an installer if the result won't work for users.

**Comment by jstayco** [comment]
All I've got for you there is my previous ask:

>I'd like to ask if I can get some limited permissions to the repository. My goals are: be able to assign installation-related issues to myself, close those issues as needed, and possibly dev write permissions if you're comfortable with that, so I can push fixes through ASAP since I'm expecting all of the bugs from all kinds of setups. 

>If you are also comfortable with it, if you give me access to the Github secrets and workflows for this repo, I can start testing out automated Docker builds and publishing capabilities.

**Comment by bmaltais** [comment]
It is just puzzling what make it work and then suddenly it does not. Hard to pin point why it will sometime train in 8bit and other time it just will Traceback.

**Comment by bmaltais** [comment]
OK, I just pushed a "destructive" commit to the dev branch that will properly train AdamW8bit on Windows as long as I do the following steps:

```
.\setup.bat
# It will fail after install because I reverted kohya_gui.py to make things work
.\venv\Scripts\activate
python .\tools\update_bitsandbytes.py
python.exe .\kohya_gui.py
```

Doing thing in that order will properly train.

I will try to upgrade kohya_gui.py to the version that was before my destructuve commit. Usually when I replace it things are falling apart... let test... if things still work I will re-introduce that part.

**Comment by bmaltais** [comment]
OK, I tested updating kohya_gui.py, redoing the steps above and AdamW8bit still work... so the current dev branch will work except the bitsandbytes files are not properly updated after the pip module installation. I guess I could fix that next.

**Comment by bmaltais** [comment]
Just as a FYI... Lot's of people are using the GUI. Here is a recent video on how to use it: https://www.youtube.com/watch?v=j-So4VYTL98

We have to be caution about releasing a very polished update for the setup and retain legacy methods for current users... last thing we should do is pull setup options they are used to and have been shown how to use them... this would create a lot of confusion and frustration.

I know we all know that, but I just wanted to point out the obvious ;-)

**Comment by bmaltais** [comment]
I fixed (rather crudely because I did not fully understood why the if statement was always false) the issue with bitsandbytes file copy.

**Comment by jstayco** [comment]
As long as it only triggers on Windows, shouldn't be a big deal.

**Comment by jstayco** [comment]
>             print(f"Copying {os.path.join(bitsandbytes_source, 'cextension.py')}")
Don't use print statements anymore. The logging facilities are there, so you can get text logs from users. If you want to always inform the user? logging.critical(msg). But this is just copying files, you want logging.debug(), so you aren't spamming the user during install.

Yeah, just took another look. All of those print statements should be logging.debu().

**Comment by bmaltais** [comment]
I added them to make sure I was not missing the statements due to debug levels... they should indeed be switched back to logging.debug now...

I am trying to run the wd14 captionning utility and I run into a weird issue with:

```
Traceback (most recent call last):
  File "D:\kohya_ss\finetune\tag_images_by_wd14_tagger.py", line 15, in <module>
    import library.train_util as train_util
```

Not sure why it no longer find the library. I notice the way the library is installed had to change dur to setup.sh being not used to setul linux... could it be causing library issues?

**Comment by jstayco** [comment]
You should never need to do that. Simply launching it as -vvv or --verbosity 3 will properly print those out with affecting any functionality. And give you text logs too, so you can quickly search them instead of scrolling through hundreds of lines of stuff.

**Comment by jstayco** [comment]
> I notice the way the library is installed had to change due to setup.sh being now used to setup linux

Not sure what you mean here. The kohya_ss library is built the normal way via pip. Only thing that changed there was setup.py -> pyproject.toml. Which should have zero effect and you check debug logs to verify if needed.

**Comment by bmaltais** [comment]
Well... wd14 captioning does not work anymore, complaining of import issue... not sure why as nothing changes in kohya_ss code.

**Comment by jstayco** [comment]
Gotta run it with debug logs. Because if pip is reporting an error during build, that's where you'll see it. Debug logs or we don't have anything to work with.

**Comment by jstayco** [comment]
> kohya-ss @ file:///D:/kohya_ss

That's the one. Name defined in pyproject.toml.

**Comment by bmaltais** [comment]
In the master branch there is an entry called

`library @ file:///E:/kohya_ss-old`

But it is missing in the dev branch

**Comment by jstayco** [comment]
That is correct. Renamed as "library" is just the folder the code is in. Project name is kohya_ss per the pyproject.toml.

**Comment by jstayco** [comment]
Yes, that was deprecated and throwing a warning every single build in every single mode. Zero reason to stay on old stuff.

**Comment by jstayco** [comment]
If you want to just do a quick test rename kohya_ss back to library in pyproject.toml :shrug:

**Comment by bmaltais** [comment]
Still failing:

```
Traceback (most recent call last):
  File "D:\kohya_ss\finetune\tag_images_by_wd14_tagger.py", line 15, in <module>
    import library.train_util as train_util
ModuleNotFoundError: No module named 'library'
```

**Comment by jstayco** [comment]
I never saw that one. Even on that Windows machine. Is there an __init__.py file in there? Maybe that's a requirement and I never noticed.

**Comment by bmaltais** [comment]
![image](https://github.com/bmaltais/kohya_ss/assets/7474674/2cd74dec-0422-413f-bf87-feb459238178)

**Comment by jstayco** [comment]
Looks normal to me.

**Comment by bmaltais** [comment]
OK... I uninstalled the kohya_ss module, deleted the pyproject.toml file and brought back the setup.py file and all is working fine now.

**Comment by jstayco** [comment]
No idea, I never had that issue. But make sure it doesn't mess up the progress bar when you run the installer.

**Comment by bmaltais** [comment]
I have pushed the crude fix to dev... this brings back functional library call until a proper fix for the library issue can be found.

**Comment by jstayco** [comment]
Once have final thumbs up and feel good about it, I'll do the other cleanup stuff I was talking about earlier.

**Comment by jstayco** [comment]
Oh yeah, and merge that other PR to (I'm hoping) detect Python 3.10 much more reliable in setup.ps1.

**Comment by bmaltais** [comment]
> Oh yeah, and merge that other PR to (I'm hoping) detect Python 3.10 much more reliable in setup.ps1.

Already did... unless the revert I made removed the change?

**Comment by jstayco** [comment]
Apologies, the GitHub UI wasn't updating for some reason like that PR was still hanging.

**Comment by jstayco** [comment]
Looks good! Only thing that's missing is the updated README that you can find here with all those formatting updates and fixes: https://github.com/jstayco/kohya_ss/blob/readme_update/README.md

**Comment by jstayco** [comment]
@wzgrx The setup.ps1 is updated. I tried to add more cases to catch unusual installations of Python or those using package managers better. Please let me know if you're still seeing issues there.

**Comment by bmaltais** [comment]
I pushed the update for the README. I was able to train a LoRA so far so good.

Will do more test tomorrow. Calling it a night.

**Comment by jstayco** [comment]
Awesome news! Thanks for all the integration testing! We'll get there to that 2.0 :laughing:

**Comment by jstayco** [comment]
Other files that were missed:
https://github.com/jstayco/kohya_ss/blob/readme_update/.dockerignore
https://github.com/jstayco/kohya_ss/blob/readme_update/.gitattributes
https://github.com/jstayco/kohya_ss/blob/readme_update/.gitignore

They account for the new config and logs folders and the .gitignore is also a more general one for Python.

**Comment by wzgrx** [comment]
I tested the installation of the new dev version and still encountered a large number of errors

Join Path: Cannot bind parameter to parameter 'Path' because it is an empty string.
Location G:  Soft  kohya_ Ss  setup. ps1: 975 Character: 41
+                 $pathPython = Join-Path $dir $candidate
+                                         ~~~~
+ CategoryInfo          : InvalidData: (:) [Join-Path]，ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Join
PathCommand
Join Path: Cannot bind parameter to parameter 'Path' because it is an empty string.
Location G:  Soft  kohya_ Ss  setup. ps1: 975 Character: 41
+                 $pathPython = Join-Path $dir $candidate
+                                         ~~~~
+ CategoryInfo          : InvalidData: (:) [Join-Path]，ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Join
PathCommand
Join Path: Cannot bind parameter to parameter 'Path' because it is an empty string.
Location G:  Soft  kohya_ Ss  setup. ps1: 975 Character: 41
+                 $pathPython = Join-Path $dir $candidate
+                                         ~~~~
+ CategoryInfo          : InvalidData: (:) [Join-Path]，ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Join
PathCommand
Join Path: Cannot bind parameter to parameter 'Path' because it is an empty string.
Location G:  Soft  kohya_ Ss  setup. ps1: 975 Character: 41
+                 $pathPython = Join-Path $dir $candidate
+                                         ~~~~
+ CategoryInfo          : InvalidData: (:) [Join-Path]，ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Join
PathCommand
Join Path: Cannot bind parameter to parameter 'Path' because it is an empty string.
Location G:  Soft  kohya_ Ss  setup. ps1: 975 Character: 41
+                 $pathPython = Join-Path $dir $candidate
+                                         ~~~~
+ CategoryInfo          : InvalidData: (:) [Join-Path]，ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Join
PathCommand
Join Path: Cannot bind parameter to parameter 'Path' because it is an empty string.
Location G:  Soft  kohya_ Ss  setup. ps1: 975 Character: 41
+                 $pathPython = Join-Path $dir $candidate
+                                         ~~~~
+ CategoryInfo          : InvalidData: (:) [Join-Path]，ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Join
PathCommand
Join Path: Cannot bind parameter to parameter 'Path' because it is an empty string.
Location G:  Soft  kohya_ Ss  setup. ps1: 975 Character: 41
+                 $pathPython = Join-Path $dir $candidate
+                                         ~~~~
+ CategoryInfo          : InvalidData: (:) [Join-Path]，ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Join
PathCommand
Join Path: Cannot bind parameter to parameter 'Path' because it is an empty string.
Location G:  Soft  kohya_ Ss  setup. ps1: 975 Character: 41
+                 $pathPython = Join-Path $dir $candidate
+                                         ~~~~
+ CategoryInfo          : InvalidData: (:) [Join-Path]，ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Join
PathCommand
Join Path: Cannot bind parameter to parameter 'Path' because it is an empty string.
Location G:  Soft  kohya_ Ss  setup. ps1: 975 Character: 41
+                 $pathPython = Join-Path $dir $candidate
+                                         ~~~~
+ CategoryInfo          : InvalidData: (:) [Join-Path]，ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Join
PathCommand
Join Path: Cannot bind parameter to parameter 'Path' because it is an empty string.
Location G:  Soft  kohya_ Ss  setup. ps1: 975 Character: 41
+                 $pathPython = Join-Path $dir $candidate
+                                         ~~~~
+ CategoryInfo          : InvalidData: (:) [Join-Path]，ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Join
PathCommand
Join Path: Cannot bind parameter to parameter 'Path' because it is an empty string.
Location G:  Soft  kohya_ Ss  setup. ps1: 975 Character: 41
+                 $pathPython = Join-Path $dir $candidate
+                                         ~~~~
+ CategoryInfo          : InvalidData: (:) [Join-Path]，ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Join
PathCommand
Join Path: Cannot bind parameter to parameter 'Path' because it is an empty string.
Location G:  Soft  kohya_ Ss  setup. ps1: 975 Character: 41
+                 $pathPython = Join-Path $dir $candidate
+                                         ~~~~
+ CategoryInfo          : InvalidData: (:) [Join-Path]，ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Co

**Comment by jstayco** [comment]
Thanks for the report! I'll hunt this one down tomorrow.

**Comment by wzgrx** [comment]
> 感谢您的报告！我明天就去追这个。

Okay, thank you. I will continue testing

**Comment by bmaltais** [comment]
So far I always ran `.\setup.bat` 

I tried to run `setup.ps1` and itis gibing me this new error:

```
Installing Python 3.10. This could take a few minutes.
Write-Error: D:\kohya_ss\setup.ps1:2342:17
Line |
2342 |                  Install-Python310 -Interactive:$Params.interactive
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unsupported operating system. Please install Python 3.10 manually.
```

**Comment by jstayco** [comment]
I think the root issue should be solved as it worked fine before and I think I just messed up my detection previously. I also have multiple examples in the README on how to bypass this, the script can be bypassed altogether (just use launcher.py directly), and half the point (for me at least) was developing training wheels for a smooth UX for people who have no idea how to install all this stuff.

**Comment by bmaltais** [comment]
As long as we don't end-up installing software the user has not agreed to on their system...

**Comment by jstayco** [comment]
And that is a good point. So far I only have the countdown and logs and such for VC Redist because it required admin rights. I can most definitely put that on all of the install functions. It's nice and modular, so easy adds. As for warnings? Launcher.py (and I think I added it to kohya_gui.py?) already do a quick Python 3.10 check at the beginning. 

It doesn't check for git because git is no longer a hard requirement. If git is detected as not installed, then we just use the Github API to download the zip release of your latest release.

**Comment by jstayco** [comment]
So the plan here is: I'll fix up setup.ps1 Python detection, see what's going on with that OS detection because I haven't seen that one yet, maybe see what I can do about that chocolatey error (as that's a problem on its own), and see what I can do about better error handling if package managers fail to install $package on Windows.

@bmaltais Do you mind running it again on your machine and adding `Write-CriticalLog "OS: ${os.family}"` right before that line in main() where it calls `Install-Python310`? I haven't had it fail on a Windows box so I wonder if your value is different for some reason.

**Comment by bmaltais** [comment]
Made the change and it is giving me this:

```
PS D:\kohya_ss> .\setup.ps1
Beginning main function.                                                                                                                                                                     
Installing Python 3.10. This could take a few minutes.
CRITICAL: OS: 
Write-Error: D:\kohya_ss\setup.ps1:2344:17
Line |
2344 |                  Install-Python310 -Interactive:$Params.interactive
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unsupported operating system. Please install Python 3.10 manually.
```

**Comment by bmaltais** [comment]
I flipped it because I want users to have an easy option to install either torch v1 or v2 as they chose. Right now the installer will always ask them on windows and I would like to keep it that way until the option to install one or the other is removed.

**Comment by jstayco** [comment]
I'll make an extra file, no problem. That is a very easy use-case to cover, but you don't need to make a bunch of new files. I'm explicitly trying to trim those down by unifying everything. 

The real answer here is two fold:
1.  I need to re-engineer the part that installs Torch to only uninstall in certain scenarios within interactive mode instead of uninstalling by default (I thought interactive mode would only be a fallback). 
2. Interactive by default ONLY in the .bat file. That gives you your double click easy Windows installer. All other files can be assumed to be run from the command line or at least for those users to be able to read a README and follow instructions.

**Comment by jstayco** [comment]
If you let me know the design drivers on things like that I'll definitely work towards nice, easy to maintain, long term solutions. I say that because actions like only flipping the interactive option in some places and not others and doing other such patches like that will definitely lead to a very difficult to maintain installer full of 1 off patches everywhere that aren't documented.

**Comment by bmaltais** [comment]
I wanted the project to democratise checkpoint trraining by exposing it to users in a way that was simple and did not require too much reading... so yes, most users of the project don't really read README and just want to quickly set things up with good defaults and get training.

**Comment by bmaltais** [comment]
Something else I used to provide to users was an update.bat script that wold just run a `pip install --upgrade` to update all modules for a new release. With the current solution, short of keeping one such module, I don't know how users will do that without re-installing everything from scratch... so this is something that will be important to provide... otherwise the good old update.bat can come to the rescue.

**Comment by jstayco** [comment]
It doesn't reinstall everything from scratch, it'll just roll through and check if things are installed and skip all the things that are. Then it goes through launcher.py which will on first run install everything then skip that every time after per your request. On subsequent runs you can just pass --update or --repair and it will redo the pip operations.

> I wanted the project to democratise checkpoint training by exposing it to users in a way that was simple and did not require too much reading... so yes, most users of the project don't really read README and just want to quickly set things up with good defaults and get training by following some youtube tutorial...

We have the same driver. Then entire purpose was to eliminate every single manual step you had in the README. That's why everything is automated by default and then users can opt in to any configuration changes they wish to make.

**Comment by jstayco** [comment]
launcher.py goes one further too. If they're on the stable version of kohya_ss (your "master" branch) it'll check for a clean repo. If the repo is clean, then it git pulls the update, then re-runs the pip stuff. If it detects a repo where changes were made to files, it alerts the user and skips the git part to avoid data corruption.

**Comment by jstayco** [comment]
My intention is to say that if you let me know the drivers and design goals I can make sure to engineer a solution that is documented and easier to maintain long term. However, if one-off patches are made to fundamental infrastructure in a rigid way I can't guarantee this solution will be maintainable in the future. It's automating a lot and answering as many questions in as many places as it can, so it's important the solution stays uniform and consistent with its design.

**Comment by bmaltais** [comment]
> It doesn't reinstall everything from scratch, it'll just roll through and check if things are installed and skip all the things that are. Then it goes through launcher.py which will on first run install everything then skip that every time after per your request. On subsequent runs you can just pass --update or --repair and it will redo the pip operations.

It is just that running in --interactive it always sort of uninstalled the torch modules and it was taking as long to install all pip modules as the original setup... Perhaps it is just doing that when running in interactive mode...

**Comment by jstayco** [comment]
Yes, that is correct. That is the direct cause of me trying to tell you not to make one-off changes that have large effects like that and to let me know what you need so I can engineer it and then modify the documentation to reflect those changes made. Which is also why I stated:

> The long term answer here is two fold:
> 
>     I need to re-engineer the part that installs Torch to only uninstall in certain scenarios within interactive mode instead of uninstalling by default (I thought interactive mode would only be a fallback).
>     Interactive by default ONLY in the .bat file. Then I'll notate that in the README. That gives you your double click easy Windows installer. All other files can be assumed to be run from the command line or at least for those users to be able to read a README and follow instructions.

**Comment by jstayco** [comment]
No disrespect to the user, but this issue serves as a good example of why I am trying to funnel everyone down into just 4 scripts: #780 

I'm aware of your need to very slowly transition users, but these kinds of user requests will all but disappear once you're fully switched over to the new system (after some initial bug fixing no doubt).
